import type { BibleBookId } from "./BibleBookIcons";
import { getBibleBookIconEntry } from "./BibleBookIcons";
import { getBookSymbolDef } from "./book-symbol-registry";

export type BookCoverPromptMeta = {
  titleAr: string;
  subtitleAr: string;
  traditionalAuthorAr: string;
  meaningAr: string;
  visualSeedAr: string;
  atmosphereAr: string;
};

export const BOOK_COVER_PROMPT_REGISTRY: Record<BibleBookId, BookCoverPromptMeta> = {
  Genesis: {
    titleAr: "التكوين",
    subtitleAr: "البداية والخليقة",
    traditionalAuthorAr: "تقليديًا موسى",
    meaningAr: "سفر البدايات والخليقة والعهد الأول",
    visualSeedAr: "شجرة حياة خارجة من كتاب مفتوح تحت نور الخلق",
    atmosphereAr: "فردوسي، ذهبي، مهيب",
  },
  Exodus: {
    titleAr: "الخروج",
    subtitleAr: "التحرير والعبور",
    traditionalAuthorAr: "تقليديًا موسى",
    meaningAr: "الخروج من العبودية إلى الحرية بقيادة الله",
    visualSeedAr: "عصا نبوية وبحر منشق ونور سماوي فوق كتاب مفتوح",
    atmosphereAr: "درامي، ملوكي، خلاص",
  },
  Leviticus: {
    titleAr: "اللاويين",
    subtitleAr: "القداسة والذبائح",
    traditionalAuthorAr: "تقليديًا موسى",
    meaningAr: "شريعة العبادة والقداسة والكهنوت",
    visualSeedAr: "مذبح ذهبي وبخور مقدس وتوهج حول كتاب مفتوح",
    atmosphereAr: "قدسي، طقسي، ذهبي",
  },
  Numbers: {
    titleAr: "العدد",
    subtitleAr: "رحلة البرية",
    traditionalAuthorAr: "تقليديًا موسى",
    meaningAr: "تنظيم الشعب والسير في البرية نحو الوعد",
    visualSeedAr: "خيمة اجتماع مضيئة في صحراء واسعة فوق كتاب مفتوح",
    atmosphereAr: "صحراوي، هادئ، إرشادي",
  },
  Deuteronomy: {
    titleAr: "التثنية",
    subtitleAr: "تجديد العهد",
    traditionalAuthorAr: "تقليديًا موسى",
    meaningAr: "تكرار الشريعة وتجديد العهد قبل الدخول",
    visualSeedAr: "لوحا الشريعة مضاءان فوق صفحات كتاب قديم",
    atmosphereAr: "نبوي، رسمي، مهيب",
  },
  Joshua: {
    titleAr: "يشوع",
    subtitleAr: "دخول أرض الموعد",
    traditionalAuthorAr: "تقليديًا يشوع",
    meaningAr: "قيادة الشعب للعبور والغلبة في أرض الوعد",
    visualSeedAr: "أبواق وأرض خصبة وأسوار بعيدة تحت نور النصرة",
    atmosphereAr: "بطولي، منتصر، ذهبي",
  },
  Judges: {
    titleAr: "القضاة",
    subtitleAr: "العدل والخلاص",
    traditionalAuthorAr: "تقليديًا صموئيل",
    meaningAr: "دورات السقوط والنجاة بقيادة القضاة",
    visualSeedAr: "ميزان عدل قديم ونور سماوي فوق كتاب مفتوح",
    atmosphereAr: "جليل، تاريخي، متزن",
  },
  Ruth: {
    titleAr: "راعوث",
    subtitleAr: "الوفاء والفداء",
    traditionalAuthorAr: "تقليديًا صموئيل",
    meaningAr: "قصة أمانة ومحبة وفداء في الحصاد",
    visualSeedAr: "سنابل ذهبية وحقول ناعمة وكتاب مفتوح بنور الغروب",
    atmosphereAr: "حنون، ريفي، ذهبي",
  },
  "1Samuel": {
    titleAr: "صموئيل الأول",
    subtitleAr: "الدعوة والمسحة",
    traditionalAuthorAr: "تقليديًا صموئيل",
    meaningAr: "دعوة النبي وصعود الملكية ومسحة داود",
    visualSeedAr: "قرن زيت ومسحة مضيئة فوق كتاب مفتوح",
    atmosphereAr: "نبوي، ملكي، مقدس",
  },
  "2Samuel": {
    titleAr: "صموئيل الثاني",
    subtitleAr: "عرش داود",
    traditionalAuthorAr: "تقليديًا ناثان وجاد",
    meaningAr: "ملك داود ووعد العرش رغم السقوط",
    visualSeedAr: "عرش ملكي ذهبي مضاء فوق كتاب مفتوح",
    atmosphereAr: "ملكي، حزين نبيل، فاخر",
  },
  "1Kings": {
    titleAr: "الملوك الأول",
    subtitleAr: "المجد والحكمة",
    traditionalAuthorAr: "تقليديًا إرميا",
    meaningAr: "حكمة سليمان وبناء الهيكل وبداية الانقسام",
    visualSeedAr: "تاج ملوكي وهيكل مضيء فوق كتاب مفتوح",
    atmosphereAr: "فخم، ذهبي، سلطاني",
  },
  "2Kings": {
    titleAr: "الملوك الثاني",
    subtitleAr: "السقوط والسبي",
    traditionalAuthorAr: "تقليديًا إرميا",
    meaningAr: "انحدار المملكتين حتى السبي",
    visualSeedAr: "تاج باهت وسط ضوء مكسور وصفحات كتاب مفتوح",
    atmosphereAr: "درامي، تاريخي، مهيب",
  },
  "1Chronicles": {
    titleAr: "أخبار الأيام الأول",
    subtitleAr: "تاريخ الرجاء",
    traditionalAuthorAr: "تقليديًا عزرا",
    meaningAr: "إعادة سرد التاريخ من منظور عبادي ورجائي",
    visualSeedAr: "لفافة تاريخية مزخرفة فوق كتاب مفتوح",
    atmosphereAr: "أثري، نبيل، مخطوطي",
  },
  "2Chronicles": {
    titleAr: "أخبار الأيام الثاني",
    subtitleAr: "الهيكل والعودة",
    traditionalAuthorAr: "تقليديًا عزرا",
    meaningAr: "الهيكل والملوك حتى السبي وبداية العودة",
    visualSeedAr: "هيكل مضاء بأشعة سماوية فوق كتاب مفتوح",
    atmosphereAr: "مقدس، تاريخي، ذهبي",
  },
  Ezra: {
    titleAr: "عزرا",
    subtitleAr: "الرجوع والترميم",
    traditionalAuthorAr: "تقليديًا عزرا",
    meaningAr: "الرجوع من السبي وترميم العبادة",
    visualSeedAr: "كاتب مقدس ولفافة ترميم أمام هيكل مضاء",
    atmosphereAr: "إصلاحي، هادئ، تاريخي",
  },
  Nehemiah: {
    titleAr: "نحميا",
    subtitleAr: "بناء الأسوار",
    traditionalAuthorAr: "تقليديًا نحميا",
    meaningAr: "إعادة بناء الأسوار وحماية الجماعة",
    visualSeedAr: "أسوار أورشليم مجددة تحت نور العهد فوق كتاب مفتوح",
    atmosphereAr: "قوي، بنائي، رجائي",
  },
  Esther: {
    titleAr: "أستير",
    subtitleAr: "العناية والخلاص",
    traditionalAuthorAr: "تقليديًا مردخاي",
    meaningAr: "خلاص الشعب بتدبير إلهي خفي",
    visualSeedAr: "صولجان ملكي ملكي ووشاح ملكي فوق كتاب مفتوح",
    atmosphereAr: "ملكي، أنيق، مضيء",
  },
  Job: {
    titleAr: "أيوب",
    subtitleAr: "الصبر في الألم",
    traditionalAuthorAr: "تقليديًا أيوب أو موسى",
    meaningAr: "الإيمان وسط الألم والسؤال والرجاء",
    visualSeedAr: "رماد هادئ ونور سماوي يخترق الظلمة فوق كتاب مفتوح",
    atmosphereAr: "تأملي، عميق، درامي",
  },
  Psalms: {
    titleAr: "المزامير",
    subtitleAr: "تسبيح وصلاة",
    traditionalAuthorAr: "تقليديًا داود وآخرون",
    meaningAr: "تسبيح وتأمل وابتهال من القلب",
    visualSeedAr: "قيثارة ملكية ذهبية فوق كتاب مفتوح وأشعة عبادة",
    atmosphereAr: "شاعري، ملوكي، نوراني",
  },
  Proverbs: {
    titleAr: "الأمثال",
    subtitleAr: "حكمة الحياة",
    traditionalAuthorAr: "تقليديًا سليمان",
    meaningAr: "حكمة عملية للسلوك والحياة",
    visualSeedAr: "مصباح حكمة متوهج فوق كتاب مفتوح",
    atmosphereAr: "هادئ، حكيم، ذهبي",
  },
  Ecclesiastes: {
    titleAr: "الجامعة",
    subtitleAr: "معنى الحياة",
    traditionalAuthorAr: "تقليديًا سليمان",
    meaningAr: "تأمل فلسفي في الزمن والمعنى تحت الشمس",
    visualSeedAr: "شمس هادئة فوق أفق واسع وكتاب مفتوح",
    atmosphereAr: "تأملي، ناضج، هادئ",
  },
  SongOfSolomon: {
    titleAr: "نشيد الأنشاد",
    subtitleAr: "الحب المقدس",
    traditionalAuthorAr: "تقليديًا سليمان",
    meaningAr: "قصيدة حب وجمال وعهد",
    visualSeedAr: "وردة ملكية مضيئة فوق كتاب مفتوح في جو شاعري",
    atmosphereAr: "رومانسي مقدس، ناعم، ذهبي",
  },
  Isaiah: {
    titleAr: "إشعياء",
    subtitleAr: "رؤيا القدوس",
    traditionalAuthorAr: "تقليديًا إشعياء",
    meaningAr: "نبوة الخلاص والمسيح والقداسة",
    visualSeedAr: "جناح نوراني وسحاب مجيد فوق كتاب مفتوح",
    atmosphereAr: "نبوي، سماوي، مهيب",
  },
  Jeremiah: {
    titleAr: "إرميا",
    subtitleAr: "قلب باكٍ",
    traditionalAuthorAr: "تقليديًا إرميا",
    meaningAr: "نبوة الدموع والتحذير والرجاء",
    visualSeedAr: "إناء خزفي قديم ونور حزين فوق كتاب مفتوح",
    atmosphereAr: "مؤثر، نبوي، عميق",
  },
  Lamentations: {
    titleAr: "مراثي إرميا",
    subtitleAr: "دموع أورشليم",
    traditionalAuthorAr: "تقليديًا إرميا",
    meaningAr: "رثاء الخراب والرجوع إلى الله",
    visualSeedAr: "دمعة مضيئة وسط أطلال هادئة فوق كتاب مفتوح",
    atmosphereAr: "حزين، مهيب، شاعري",
  },
  Ezekiel: {
    titleAr: "حزقيال",
    subtitleAr: "رؤى المجد",
    traditionalAuthorAr: "تقليديًا حزقيال",
    meaningAr: "رؤى مجد الله والتجديد",
    visualSeedAr: "عجلة سماوية نارية فوق كتاب مفتوح",
    atmosphereAr: "رؤيوي، سماوي، قوي",
  },
  Daniel: {
    titleAr: "دانيال",
    subtitleAr: "الثبات في المملكة",
    traditionalAuthorAr: "تقليديًا دانيال",
    meaningAr: "أمانة في المنفى ورؤى للممالك",
    visualSeedAr: "أسد مهيب في ضوء الملكوت فوق كتاب مفتوح",
    atmosphereAr: "بطولي، نبوي، ملكي",
  },
  Hosea: {
    titleAr: "هوشع",
    subtitleAr: "حب العهد",
    traditionalAuthorAr: "تقليديًا هوشع",
    meaningAr: "محبة الله الأمينة لشعبه رغم الخيانة",
    visualSeedAr: "رمز عهد مضيء وقلب مستعاد فوق كتاب مفتوح",
    atmosphereAr: "عاطفي، نبوي، رحيم",
  },
  Joel: {
    titleAr: "يوئيل",
    subtitleAr: "يوم الرب",
    traditionalAuthorAr: "تقليديًا يوئيل",
    meaningAr: "دعوة للتوبة مع وعد الروح",
    visualSeedAr: "جراد رمزي يتحول إلى نور واستعادة فوق كتاب مفتوح",
    atmosphereAr: "إنذاري، متحوّل، ذهبي",
  },
  Amos: {
    titleAr: "عاموس",
    subtitleAr: "العدل الإلهي",
    traditionalAuthorAr: "تقليديًا عاموس",
    meaningAr: "نداء قوي للعدل والحق",
    visualSeedAr: "مطمار عدل متوهج فوق كتاب مفتوح",
    atmosphereAr: "قوي، صارم، نبوي",
  },
  Obadiah: {
    titleAr: "عوبديا",
    subtitleAr: "سقوط الكبرياء",
    traditionalAuthorAr: "تقليديًا عوبديا",
    meaningAr: "دينونة الكبرياء وعلو الرب",
    visualSeedAr: "جبل شامخ تحت نور الدينونة فوق كتاب مفتوح",
    atmosphereAr: "جليل، قوي، نبوي",
  },
  Jonah: {
    titleAr: "يونان",
    subtitleAr: "الرحمة والدعوة",
    traditionalAuthorAr: "تقليديًا يونان",
    meaningAr: "رحمة الله للأمم ودعوة النبي",
    visualSeedAr: "سمكة عظيمة ونور توبة فوق كتاب مفتوح",
    atmosphereAr: "بحري، رمزي، رحيم",
  },
  Micah: {
    titleAr: "ميخا",
    subtitleAr: "الحق والعدل",
    traditionalAuthorAr: "تقليديًا ميخا",
    meaningAr: "العدل والرحمة والسلوك المتواضع",
    visualSeedAr: "ميزان مضيء فوق كتاب مفتوح وسط نور هادئ",
    atmosphereAr: "نبوي، نقي، متزن",
  },
  Nahum: {
    titleAr: "ناحوم",
    subtitleAr: "حصن المؤمنين",
    traditionalAuthorAr: "تقليديًا ناحوم",
    meaningAr: "قضاء على الشر وتعزية للمؤمنين",
    visualSeedAr: "ترس حصين مضاء فوق كتاب مفتوح",
    atmosphereAr: "قوي، حصين، درامي",
  },
  Habakkuk: {
    titleAr: "حبقوق",
    subtitleAr: "الإيمان والانتظار",
    traditionalAuthorAr: "تقليديًا حبقوق",
    meaningAr: "الوقوف في البرج وانتظار جواب الله",
    visualSeedAr: "برج مراقبة مضاء فوق كتاب مفتوح عند الفجر",
    atmosphereAr: "تأملي، مترقب، نبوي",
  },
  Zephaniah: {
    titleAr: "صفنيا",
    subtitleAr: "تطهير وتجديد",
    traditionalAuthorAr: "تقليديًا صفنيا",
    meaningAr: "يوم الرب وتطهير البقية",
    visualSeedAr: "نار مقدسة تنقي المشهد فوق كتاب مفتوح",
    atmosphereAr: "نبوي، ناري، مهيب",
  },
  Haggai: {
    titleAr: "حجي",
    subtitleAr: "بناء الهيكل",
    traditionalAuthorAr: "تقليديًا حجي",
    meaningAr: "دعوة لإعادة بناء بيت الله",
    visualSeedAr: "هيكل قيد البناء تحت أشعة المجد فوق كتاب مفتوح",
    atmosphereAr: "مشجّع، ذهبي، مقدس",
  },
  Zechariah: {
    titleAr: "زكريا",
    subtitleAr: "رؤى الرجاء",
    traditionalAuthorAr: "تقليديًا زكريا",
    meaningAr: "رؤى تجديد ومسيا آتٍ",
    visualSeedAr: "منارة ذهبية مضيئة فوق كتاب مفتوح",
    atmosphereAr: "رؤيوي، ذهبي، رجائي",
  },
  Malachi: {
    titleAr: "ملاخي",
    subtitleAr: "شمس البر",
    traditionalAuthorAr: "تقليديًا ملاخي",
    meaningAr: "أمانة العهد ووعد شمس البر",
    visualSeedAr: "شمس بر متألقة فوق كتاب مفتوح",
    atmosphereAr: "ختامي، نوراني، ذهبي",
  },
  Matthew: {
    titleAr: "متى",
    subtitleAr: "إنجيل ملكوت المسيح",
    traditionalAuthorAr: "تقليديًا متى الرسول",
    meaningAr: "المسيح الملك المتمم للنبوات",
    visualSeedAr: "تاج ملوكي فوق كتاب مفتوح تحت أشعة الملكوت",
    atmosphereAr: "ملكي، ذهبي، إنجيلي",
  },
  Mark: {
    titleAr: "مرقس",
    subtitleAr: "إنجيل ابن الله",
    traditionalAuthorAr: "تقليديًا مرقس",
    meaningAr: "المسيح القوي المتألم وابن الله",
    visualSeedAr: "أسد مهيب في نور سماوي فوق أرض مقدسة",
    atmosphereAr: "قوي، ملكي، جريء",
  },
  Luke: {
    titleAr: "لوقا",
    subtitleAr: "الطبيب المحبوب",
    traditionalAuthorAr: "تقليديًا لوقا",
    meaningAr: "إنجيل الرحمة والشفاء والإنسانية",
    visualSeedAr: "ثور مقدس هادئ قرب كتاب ولفافة في نور ذهبي",
    atmosphereAr: "رحيم، إنساني، دافئ",
  },
  John: {
    titleAr: "يوحنا",
    subtitleAr: "الإنجيل المحبوب",
    traditionalAuthorAr: "تقليديًا يوحنا الرسول",
    meaningAr: "إعلان لاهوت المسيح والحياة الأبدية",
    visualSeedAr: "نسر مهيب فوق كتاب مفتوح في ضوء سماوي نازل",
    atmosphereAr: "سماوي، عميق، لاهوتي",
  },
  Acts: {
    titleAr: "أعمال الرسل",
    subtitleAr: "انتشار الكنيسة الأولى",
    traditionalAuthorAr: "تقليديًا لوقا",
    meaningAr: "انطلاق الرسالة بقوة الروح القدس",
    visualSeedAr: "مفاتيح رسولية ذهبية فوق كتاب مفتوح وأشعة إرسالية",
    atmosphereAr: "متحرك، رسولي، ذهبي",
  },
  Romans: {
    titleAr: "رومية",
    subtitleAr: "البر بالإيمان",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "أعمق عرض للإنجيل والنعمة والبر",
    visualSeedAr: "صليب مضاء على تل فوق كتاب مفتوح",
    atmosphereAr: "لاهوتي، مهيب، عميق",
  },
  "1Corinthians": {
    titleAr: "كورنثوس الأولى",
    subtitleAr: "الكنيسة والقداسة",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "تصحيح حياة الكنيسة ووحدة الجسد",
    visualSeedAr: "عمود كنيسة قوي فوق كتاب مفتوح",
    atmosphereAr: "رسولي، معماري، رصين",
  },
  "2Corinthians": {
    titleAr: "كورنثوس الثانية",
    subtitleAr: "تعزية وخدمة",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "قوة الله في الضعف وخدمة المصالحة",
    visualSeedAr: "رسالة مضاءة بختم رسولي فوق كتاب مفتوح",
    atmosphereAr: "شخصي، مؤثر، رسولي",
  },
  Galatians: {
    titleAr: "غلاطية",
    subtitleAr: "حرية الإنجيل",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "الحرية في المسيح لا في الناموس",
    visualSeedAr: "قيود مكسورة يعلوها نور فوق كتاب مفتوح",
    atmosphereAr: "تحرري، قوي، ذهبي",
  },
  Ephesians: {
    titleAr: "أفسس",
    subtitleAr: "سر الكنيسة",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "هوية الكنيسة ووحدتها في المسيح",
    visualSeedAr: "كنيسة نورانية متألقة فوق كتاب مفتوح",
    atmosphereAr: "كنسي، سماوي، فاخر",
  },
  Philippians: {
    titleAr: "فيلبي",
    subtitleAr: "رسالة الفرح",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "فرح وثبات في المسيح وسط الضيق",
    visualSeedAr: "مرساة مضيئة في نور السلام فوق كتاب مفتوح",
    atmosphereAr: "مشرق، ثابت، هادئ",
  },
  Colossians: {
    titleAr: "كولوسي",
    subtitleAr: "سمو المسيح",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "سيادة المسيح وكفايته",
    visualSeedAr: "تاج وصليب مجيد فوق كتاب مفتوح",
    atmosphereAr: "سامٍ، ملوكي، لاهوتي",
  },
  "1Thessalonians": {
    titleAr: "تسالونيكي الأولى",
    subtitleAr: "رجاء المجيء",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "رجاء وسهر في انتظار الرب",
    visualSeedAr: "فجر روحي يشرق فوق كتاب مفتوح",
    atmosphereAr: "رجائي، مضيء، رقيق",
  },
  "2Thessalonians": {
    titleAr: "تسالونيكي الثانية",
    subtitleAr: "ثبات وتمييز",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "ثبات أمام الاضطراب وتمييز الأزمنة",
    visualSeedAr: "ترس مضيء يحمي كتابًا مفتوحًا",
    atmosphereAr: "ثابت، وقور، قوي",
  },
  "1Timothy": {
    titleAr: "تيموثاوس الأولى",
    subtitleAr: "الراعي الأمين",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "تنظيم الكنيسة وخدمة الراعي",
    visualSeedAr: "عصا راعٍ مضيئة فوق كتاب مفتوح",
    atmosphereAr: "رعوي، هادئ، منظم",
  },
  "2Timothy": {
    titleAr: "تيموثاوس الثانية",
    subtitleAr: "الجهاد الحسن",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "الثبات في الدعوة حتى النهاية",
    visualSeedAr: "سيف روحي متوهج فوق كتاب مفتوح",
    atmosphereAr: "شجاع، وداعي، نبيل",
  },
  Titus: {
    titleAr: "تيطس",
    subtitleAr: "ترتيب الخدمة",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "تنظيم الكنائس والأعمال الصالحة",
    visualSeedAr: "كنيسة منظمة ونور خدمة فوق كتاب مفتوح",
    atmosphereAr: "منظم، كنسي، هادئ",
  },
  Philemon: {
    titleAr: "فليمون",
    subtitleAr: "غفران ومصالحة",
    traditionalAuthorAr: "تقليديًا بولس",
    meaningAr: "المحبة المسيحية في المصالحة",
    visualSeedAr: "مصافحة مضيئة فوق كتاب مفتوح",
    atmosphereAr: "إنساني، دافئ، حميم",
  },
  Hebrews: {
    titleAr: "العبرانيين",
    subtitleAr: "الكهنوت الأعظم",
    traditionalAuthorAr: "تقليديًا بولس أو مجهول",
    meaningAr: "المسيح رئيس الكهنة الكامل",
    visualSeedAr: "حجاب مقدس ونور قدس الأقداس فوق كتاب مفتوح",
    atmosphereAr: "مقدس، لاهوتي، مهيب",
  },
  James: {
    titleAr: "يعقوب",
    subtitleAr: "الإيمان العامل",
    traditionalAuthorAr: "تقليديًا يعقوب",
    meaningAr: "حكمة عملية وإيمان يظهر في العمل",
    visualSeedAr: "ريشة كاتب وحكمة مضيئة فوق كتاب مفتوح",
    atmosphereAr: "حكيم، عملي، هادئ",
  },
  "1Peter": {
    titleAr: "بطرس الأولى",
    subtitleAr: "رجاء في الألم",
    traditionalAuthorAr: "تقليديًا بطرس",
    meaningAr: "تعزية وثبات وسط الاضطهاد",
    visualSeedAr: "مرساة وإشارة إيمان فوق كتاب مفتوح",
    atmosphereAr: "مثبّت، هادئ، مؤمن",
  },
  "2Peter": {
    titleAr: "بطرس الثانية",
    subtitleAr: "النمو والحق",
    traditionalAuthorAr: "تقليديًا بطرس",
    meaningAr: "النمو الروحي والثبات في الحق",
    visualSeedAr: "غصن نامٍ بنور سماوي فوق كتاب مفتوح",
    atmosphereAr: "نامٍ، نقي، مشرق",
  },
  "1John": {
    titleAr: "يوحنا الأولى",
    subtitleAr: "المحبة والنور",
    traditionalAuthorAr: "تقليديًا يوحنا الرسول",
    meaningAr: "يقين الحياة في المحبة والحق",
    visualSeedAr: "قلب مضاء بالنور فوق كتاب مفتوح",
    atmosphereAr: "حنون، نوراني، عميق",
  },
  "2John": {
    titleAr: "يوحنا الثانية",
    subtitleAr: "الحق والمحبة",
    traditionalAuthorAr: "تقليديًا يوحنا الرسول",
    meaningAr: "الثبات في الحق مع المحبة",
    visualSeedAr: "ختم رسالة مقدسة فوق كتاب مفتوح",
    atmosphereAr: "رشيق، نقي، رسائلي",
  },
  "3John": {
    titleAr: "يوحنا الثالثة",
    subtitleAr: "الضيافة الأمينة",
    traditionalAuthorAr: "تقليديًا يوحنا الرسول",
    meaningAr: "الحق العملي في الضيافة والخدمة",
    visualSeedAr: "بيت مضيء مفتوح للضيوف فوق كتاب مفتوح",
    atmosphereAr: "دافئ، مرحّب، هادئ",
  },
  Jude: {
    titleAr: "يهوذا",
    subtitleAr: "الجهاد للإيمان",
    traditionalAuthorAr: "تقليديًا يهوذا",
    meaningAr: "الثبات والدفاع عن الإيمان",
    visualSeedAr: "درع إيمان متوهج فوق كتاب مفتوح",
    atmosphereAr: "حازم، قوي، رسائلي",
  },
  Revelation: {
    titleAr: "رؤيا يوحنا اللاهوتي",
    subtitleAr: "مجد الملكوت",
    traditionalAuthorAr: "تقليديًا يوحنا الرسول",
    meaningAr: "رؤى النهاية وغلبة الحمل والملكوت",
    visualSeedAr: "تاج مجيد ونور سماوي نازل فوق كتاب مفتوح",
    atmosphereAr: "رؤيوي، ذهبي، مهيب جدًا",
  },
};

const REFERENCE_STYLE_AR =
  "غلاف مربع فاخر شديد اللمعان بأسلوب الصور المرجعية، حواف زجاجية ناعمة، بطاقة جلاسي ثلاثية الأبعاد، مشهد علوي سينمائي مقدس، أشعة نور سماوية ذهبية، سحب كريمية، واقعية عالية جدًا، لوحة سفلية داكنة شفافة للنص، توزيع متناظر، فخامة مسيحية شرقية، بدون واترمارك";

export function buildBookCoverPrompt(bookId: BibleBookId): string {
  const meta = BOOK_COVER_PROMPT_REGISTRY[bookId];
  const icon = getBibleBookIconEntry(bookId);
  const symbol = getBookSymbolDef(bookId);

  return [
    REFERENCE_STYLE_AR,
    `السفر: ${meta.titleAr}.`,
    `العنوان الفرعي: ${meta.subtitleAr}.`,
    `الكاتب التقليدي: ${meta.traditionalAuthorAr}.`,
    `المعنى: ${meta.meaningAr}.`,
    `الرمز المركزي المقترح: ${meta.visualSeedAr}.`,
    `الجو العام: ${meta.atmosphereAr}.`,
    `التصنيف: ${symbol.categoryAr}.`,
    `لون المشهد الرئيسي قريب من ${symbol.color} مع إضاءات ${symbol.colorLight}.`,
    `استخدم منطق السفر ${icon?.bookName ?? meta.titleAr} لصناعة مشهد رمزي احترافي ومترابط مع الكاتب والرسالة.`,
    `ادمج داخل الغلاف نصًا عربيًا أنيقًا: العنوان الكبير '${meta.titleAr}' في اللوحة السفلية، وتحتها العنوان الفرعي '${meta.subtitleAr}'.`,
    "أبقِ نفس تقسيم الصورة المرجعية: مشهد رمزي كبير في الأعلى، شارة ملكية أو تفصيلة ذهبية في الوسط، ثم لوحة سفلية نصية فاخرة.",
    "يجب أن تكون الصورة بدقة عالية جدًا، مناسبة كغلاف سفر داخل تطبيق موبايل فاخر، مع وضوح ممتاز للنص والعناصر.",
  ].join(" ");
}

