import type { Saint } from "./types";
import saintShenouda from "@/assets/synaxarium/saint-shenouda.jpg";
import saintAntony from "@/assets/synaxarium/saint-antony.jpg";

export const SAINTS: Saint[] = [
  {
    id: "shenouda",
    name: "القديس شنودة رئيس المتوحدين",
    title: "الراهب العظيم، أب الرهبان",
    feast: "اليوم: استشهاد القديس شنودة رئيس المتوحدين",
    gregorianDate: "الجمعة 15 مايو 2026",
    copticDate: "7 بشنس 1742",
    liturgicalColor: "أخضر",
    liturgicalColorHex: "#3e7a55",
    summary: "أب الرهبان وأحد أعمدة الرهبنة القبطية في البرية المصرية.",
    quote: "إن كنت تريد أن تصير كاملاً، فاذهب وبعْ كل ما لك وتعال اتبعني.",
    quoteRef: "(مت 21:29)",
    reposeDate: "حوالي 466 م",
    reposePlace: "برية شيهيت",
    service: "راهب ومتوحد",
    commemoration: "7 بشنس",
    bio: "القديس شنودة رئيس المتوحدين هو أب الرهبان في البرية المصرية. عاش حياة نسكية صارمة في البرية منذ صغره، وصار مثالاً في الزهد والطاعة والصلاة. جمع حوله الكثير من التلاميذ والرهبان، ووضع لهم قوانين الرهبنة. له العديد من الأقوال الروحية النافعة.",
    events: [
      { year: "348 م", text: "ولد في قرية شندويل بصعيد مصر." },
      { year: "370 م", text: "ترهب على يد خاله الأنبا بجول." },
      { year: "385 م", text: "صار رئيساً للدير الأبيض." },
      { year: "431 م", text: "حضر مجمع أفسس مع البابا كيرلس." },
      { year: "466 م", text: "تنيح بسلام عن عمر يناهز 118 سنة." },
    ],
    image: saintShenouda,
  },
  {
    id: "antony",
    name: "القديس أنبا أنطونيوس الكبير",
    title: "أب الرهبنة في العالم كله",
    feast: "تذكار نياحة الأنبا أنطونيوس",
    gregorianDate: "السبت 30 يناير 2026",
    copticDate: "22 طوبه 1742",
    liturgicalColor: "أبيض",
    liturgicalColorHex: "#b8893a",
    summary: "أب الرهبنة المسيحية وقدوة المتوحدين في كل العصور.",
    quote: "لا تخف يا أنطونيوس، فأنا معك في كل حين.",
    quoteRef: "(صوت من السماء)",
    reposeDate: "356 م",
    reposePlace: "جبل القلزم",
    service: "أب الرهبان",
    commemoration: "22 طوبه",
    bio: "ولد الأنبا أنطونيوس في قرية قمن العروس بمصر، ومن صغره أحب حياة العبادة. باع كل ما يملك وتفرغ للنسك، فصار أباً لرهبان البرية. عاش 105 سنوات، أمضى أكثرها في البرية متعبداً.",
    events: [
      { year: "251 م", text: "ولد في قرية قمن العروس." },
      { year: "271 م", text: "سمع كلمة الإنجيل وباع كل ما يملك." },
      { year: "285 م", text: "انفرد في القبور للنسك والصلاة." },
      { year: "311 م", text: "نزل إلى الإسكندرية لتشجيع الشهداء." },
      { year: "356 م", text: "تنيح بسلام في جبل القلزم." },
    ],
    image: saintAntony,
  },
  {
    id: "shenouda-2",
    name: "القديس مكاريوس الكبير",
    title: "كوكب البرية، أب رهبان شيهيت",
    feast: "تذكار نياحة الأنبا مكاريوس الكبير",
    gregorianDate: "الأحد 7 فبراير 2026",
    copticDate: "27 طوبه 1742",
    liturgicalColor: "أبيض",
    liturgicalColorHex: "#b8893a",
    summary: "كوكب البرية وأحد أعظم رهبان شيهيت.",
    quote: "إن صلّيت بفمك وقلبك متشتت فلا فائدة من صلاتك.",
    quoteRef: "(أقوال الآباء)",
    reposeDate: "390 م",
    reposePlace: "برية شيهيت",
    service: "راهب وأب روحي",
    commemoration: "27 طوبه",
    bio: "ولد القديس مكاريوس الكبير في قرية شبشير بمصر. اشتهر بنسكه الشديد وحكمته العميقة. جمع حوله الرهبان وأسس برية شيهيت التي صارت منارة للرهبنة في العالم.",
    events: [
      { year: "300 م", text: "ولد في قرية شبشير." },
      { year: "330 م", text: "ترك العالم وتوجه إلى البرية." },
      { year: "360 م", text: "أسس دير القديس مكاريوس بشيهيت." },
      { year: "390 م", text: "تنيح بسلام عن عمر 90 سنة." },
    ],
    image: saintAntony,
  },
];

export const getSaint = (id: string) => SAINTS.find((s) => s.id === id) ?? SAINTS[0];
export const getTodaySaint = () => SAINTS[0];
