import type { BibleBookId } from "@/lib/bible-icons";
import { bookDescription } from "@/lib/book-meta";

/** Rich one-line meaning per book — shown under title on premium cards. */
const PREMIUM_MEANINGS: Partial<Record<BibleBookId, string>> = {
  Genesis: "بداية الخليقة · سقوط الإنسان · وعد الله لإبراهيم",
  Exodus: "تحرير من مصر · الشريعة · خيمة اللقاء",
  Leviticus: "القداسة والذبيحة · طريق العبادة",
  Numbers: "رحلة الشعب في البرية · الوفاء بالعهد",
  Deuteronomy: "تذكير الشريعة قبل الأرض الموعودة",
  Joshua: "دخول الأرض · انتصار الإيمان",
  Judges: "دورات الضعف والنجاة",
  Ruth: "ولاء ومحبة · خط موعود",
  "1Samuel": "صموئيل · شاول · داود النبى الملك",
  "2Samuel": "ملك داود · عهد الله الأبدي",
  "1Kings": "سليomon والحكمة · بنيان الهيكل",
  "2Kings": "انقسام الممالك · أنبياء وعدالة",
  "1Chronicles": "سلسلة العهد · عبادة وتاريخ",
  "2Chronicles": "الهيكل · ملوك يهوذا",
  Ezra: "عودة من السبي · بناء الهيكل",
  Nehemiah: "إعادة بناء السور · ثبات الشعب",
  Tobit: "رحمة الله · إيمان طوبيا وسارة",
  Judith: "شجاعة · خلاص شعب الله",
  Esther: "خلاص خفي في قلب الإمبراطورية",
  "1Maccabees": "شهادة المكابيين · حرية العبادة",
  "2Maccabees": "استشهاد · أمل بالقيامة",
  Job: "برّ في الاختبار · سؤال الألم",
  Psalms: "تسبيح · دعاء · رجاء · توبة",
  Proverbs: "حكمة عملية للحياة اليومية",
  Ecclesiastes: "معنى الحياة تحت الشمس",
  SongOfSolomon: "نشيد المحبة والعهد",
  Wisdom: "حكمة الله في الخليقة والتاريخ",
  Sirach: "حكمة عملية · تعليم الأبناء",
  Isaiah: "نبوءة المسيح · راحة · خلاص",
  Jeremiah: "نبوءة هدم وبناء جديد",
  Lamentations: "بكاء على أورشليم",
  Baruch: "رجاء بعد الهدم · صلاة الجيل",
  Ezekiel: "رؤى ومجد · قلب جديد",
  Daniel: "إيمان في ممالك البشر",
  Hosea: "محبة وفidelity رغم الخيانة",
  Joel: "يوم الرب · الروح على كل جسد",
  Amos: "عدالة الله للأمم",
  Obadiah: "قضاء على الكبرياء",
  Jonah: "رحمة الله الواسعة",
  Micah: "ما يرضي الرب · موعد بيت لحم",
  Nahum: "قضاء على نينوى",
  Habakkuk: "إيمان يثبت رغم الظلام",
  Zephaniah: "يوم الرب · فرح الخلاص",
  Haggai: "أولوية بيت الرب",
  Zechariah: "رؤى المسيح الآتي",
  Malachi: "عهد أخير قبل يوحنا",
  Matthew: "ملكوت السموات · يسوع ابن داود",
  Mark: "خدمة المسيح · فداء سريع",
  Luke: "خلاص للعالم · محبوب للخطاة",
  John: "الكلمة صار جسداً · حياة أبدية",
  Acts: "الروح القدس · امتداد الكنيسة",
  Romans: "برّ الله بالإيمان",
  "1Corinthians": "كنيسة · مواهب · محبة",
  "2Corinthians": "خدمة · توبة · فرح",
  Galatians: "حرية المسيح من الناموس",
  Ephesians: "كنيسة · وحدة · درع الله",
  Philippians: "فرح في المسيح يسوع",
  Colossians: "علوّ المسيح · كمال",
  "1Thessalonians": "انتظار مجيء الرب",
  "2Thessalonians": "يقظة وثبات",
  "1Timothy": "رعاية الكنيسة بأمانة",
  "2Timothy": "شهادة حتى النهاية",
  Titus: "تعليم سليم · حسن أعمال",
  Philemon: "غفران · محبة · إخوة",
  Hebrews: "كهنوت المسيح الأعلى",
  James: "إيمان حيّ · أعمال",
  "1Peter": "رجاء في وسط الاضطهاد",
  "2Peter": "نمو · انتظار",
  "1John": "محبة · نور · حق",
  "2John": "السلام بالحق",
  "3John": "ضيافة الرسل",
  Jude: "الإيمان المحفوظ للقديسين",
  Revelation: "انتصار الحمل · ملكوت أبدي",
};

export function getBookPremiumMeaning(bookId: BibleBookId, bookParam: string): string {
  return PREMIUM_MEANINGS[bookId] ?? bookDescription(bookParam);
}
