import type { FeastEvent, FeastCategory } from "./types";
import feastCovenant from "@/assets/feasts/feast-covenant.jpg";
import feastResurrection from "@/assets/feasts/feast-resurrection.jpg";
import { heavenlyChurch, churchChalice, churchPeople, churchBell } from "@/assets/home";

export const FEASTS: FeastEvent[] = [
  {
    id: "covenant",
    title: "خميس العهد",
    subtitle: "ذكرى العشاء السري",
    category: "feast",
    copticDay: "17",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    scripture: '"تعالوا إليّ يا جميع المُتعَبين والثَقيلي الأَحمال، وأنا أُريحُكم."',
    scriptureRef: "متى 11:28",
    description: "ذكرى العشاء السري الذي أسس فيه الرب سر الإفخارستيا.",
    about: "في هذا اليوم نتذكر العشاء الأخير الذي أسس فيه السيد المسيح سر التناول، وغسل أرجل تلاميذه ليعلمنا التواضع.",
    rite: "قداس خميس العهد يقام في المساء بعد غسل الأرجل، وفيه يُكرَّس الميرون كل سبع سنوات.",
    readings: "إنجيل يوحنا 13 — رسالة كورنثوس الأولى 11.",
    image: feastCovenant,
    accent: "purple",
  },
  {
    id: "good-friday",
    title: "الجمعة العظيمة",
    subtitle: "ذكرى آلام وصلب السيد المسيح",
    category: "feast",
    copticDay: "18",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "اليوم الذي صُلب فيه السيد المسيح من أجل خلاص العالم.",
    about: "نتذكر فيه آلام الرب وصلبه وموته من أجل خلاص الجنس البشري.",
    rite: "صلوات الساعات السبع وقراءة سفر النبوات والمزامير.",
    readings: "إنجيل البصخة المقدسة — متى 27 ومرقس 15.",
    image: churchChalice,
    accent: "gold",
  },
  {
    id: "bright-saturday",
    title: "سبت النور",
    subtitle: "ذكرى نزول النور المقدس",
    category: "feast",
    copticDay: "19",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "اليوم الذي نزل فيه الرب إلى الجحيم وحرر النفوس.",
    about: "في هذا اليوم نزل الرب إلى الجحيم وحرر آدم وحواء والآباء البررة.",
    rite: "قداس خاص بطقس البصخة وإنارة الكنيسة بالنور المقدس.",
    readings: "تكوين 1 — أعمال الرسل 1.",
    image: heavenlyChurch,
    accent: "gold",
  },
  {
    id: "resurrection",
    title: "عيد القيامة المجيد",
    subtitle: "أعظم أعيادنا، قام المسيح بالحقيقة قام",
    category: "feast",
    copticDay: "20",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    scripture: '"المسيح قام، بالحقيقة قام."',
    scriptureRef: "تحية القيامة",
    description: "أعظم أعياد المسيحية، قيامة الرب من الأموات.",
    about: "قيامة الرب يسوع المسيح من الأموات هي أساس إيماننا وأعظم أعيادنا.",
    rite: "قداس عيد القيامة بطقس فرايحي مميز ودورة القيامة حول الكنيسة.",
    readings: "متى 28 — مرقس 16 — لوقا 24 — يوحنا 20.",
    image: feastResurrection,
    accent: "green",
  },
  {
    id: "palm-sunday",
    title: "أحد الشعانين",
    subtitle: "ذكرى دخول السيد المسيح أورشليم",
    category: "feast",
    copticDay: "22",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "دخول الرب يسوع المسيح إلى أورشليم على جحش ابن أتان.",
    about: "نتذكر دخول الرب أورشليم وكيف استقبله الشعب بسعف النخيل والترانيم.",
    rite: "دورة الشعانين بسعف النخيل وقراءة البشارات الأربع.",
    readings: "متى 21 — مرقس 11 — لوقا 19 — يوحنا 12.",
    image: churchPeople,
    accent: "green",
  },
  {
    id: "thomas-sunday",
    title: "أحد توما",
    subtitle: "ذكرى ظهور السيد المسيح لتوما",
    category: "feast",
    copticDay: "24",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "ظهور الرب للقديس توما الرسول بعد القيامة بثمانية أيام.",
    about: "ظهر الرب لتلاميذه ومعهم توما، وأكد له قيامته فآمن وقال 'ربي وإلهي'.",
    rite: "قداس أحد توما بطقس الخمسين المقدسة.",
    readings: "يوحنا 20 — أعمال 5.",
    image: churchBell,
    accent: "blue",
  },
];

export const getFeast = (id: string) => FEASTS.find((f) => f.id === id) ?? FEASTS[0];
export const getTodayFeast = () => FEASTS[0];

export const CATEGORIES: { id: FeastCategory | "all"; label: string }[] = [
  { id: "all", label: "الكل" },
  { id: "feast", label: "الأعياد" },
  { id: "fast", label: "أصوام" },
  { id: "saint", label: "قديسين" },
  { id: "occasion", label: "مناسبات" },
];
