import type { FeastEvent, FeastCategory } from "./types";
import feastLastSupper from "@/assets/feasts/feast-last-supper.jpg";
import feastCrucifixion from "@/assets/feasts/feast-crucifixion.jpg";
import feastHolyLight from "@/assets/feasts/feast-holy-light.jpg";
import feastEmptyTomb from "@/assets/feasts/feast-empty-tomb.jpg";
import feastPalmSunday from "@/assets/feasts/feast-palm-sunday.jpg";
import feastThomas from "@/assets/feasts/feast-thomas.jpg";

export const FEASTS: FeastEvent[] = [
  {
    id: "covenant",
    title: "خميس العهد",
    subtitle: "ذكرى العشاء السري",
    category: "feast",
    copticDay: "17",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    scripture: '"تعالوا إليّ يا جميع المُتعَبين والثَقيلي الأَحمال، وأنا أُريحُكم."',
    scriptureRef: "متى 11:28",
    description: "ذكرى العشاء السري الذي أسس فيه الرب سر الإفخارستيا.",
    about: "في هذا اليوم نتذكر العشاء الأخير الذي أسس فيه السيد المسيح سر التناول، وغسل أرجل تلاميذه ليعلمنا التواضع.",
    rite: "قداس خميس العهد يقام في المساء بعد غسل الأرجل، وفيه يُكرَّس الميرون كل سبع سنوات.",
    readings: "إنجيل يوحنا 13 — رسالة كورنثوس الأولى 11.",
    image: feastLastSupper,
    accent: "purple",
  },
  {
    id: "good-friday",
    title: "الجمعة العظيمة",
    subtitle: "ذكرى آلام وصلب السيد المسيح",
    category: "feast",
    copticDay: "18",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "اليوم الذي صُلب فيه السيد المسيح من أجل خلاص العالم.",
    about: "نتذكر فيه آلام الرب وصلبه وموته من أجل خلاص الجنس البشري.",
    rite: "صلوات الساعات السبع وقراءة سفر النبوات والمزامير.",
    readings: "إنجيل البصخة المقدسة — متى 27 ومرقس 15.",
    image: feastCrucifixion,
    accent: "gold",
  },
  {
    id: "bright-saturday",
    title: "سبت النور",
    subtitle: "ذكرى نزول النور المقدس",
    category: "feast",
    copticDay: "19",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "اليوم الذي نزل فيه الرب إلى الجحيم وحرر النفوس.",
    about: "في هذا اليوم نزل الرب إلى الجحيم وحرر آدم وحواء والآباء البررة.",
    rite: "قداس خاص بطقس البصخة وإنارة الكنيسة بالنور المقدس.",
    readings: "تكوين 1 — أعمال الرسل 1.",
    image: feastHolyLight,
    accent: "gold",
  },
  {
    id: "resurrection",
    title: "عيد القيامة المجيد",
    subtitle: "أعظم أعيادنا، قام المسيح بالحقيقة قام",
    category: "feast",
    copticDay: "20",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    scripture: '"المسيح قام، بالحقيقة قام."',
    scriptureRef: "تحية القيامة",
    description: "أعظم أعياد المسيحية، قيامة الرب من الأموات.",
    about: "قيامة الرب يسوع المسيح من الأموات هي أساس إيماننا وأعظم أعيادنا.",
    rite: "قداس عيد القيامة بطقس فرايحي مميز ودورة القيامة حول الكنيسة.",
    readings: "متى 28 — مرقس 16 — لوقا 24 — يوحنا 20.",
    image: feastEmptyTomb,
    accent: "green",
  },
  {
    id: "palm-sunday",
    title: "أحد الشعانين",
    subtitle: "ذكرى دخول السيد المسيح أورشليم",
    category: "feast",
    copticDay: "22",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "دخول الرب يسوع المسيح إلى أورشليم على جحش ابن أتان.",
    about: "نتذكر دخول الرب أورشليم وكيف استقبله الشعب بسعف النخيل والترانيم.",
    rite: "دورة الشعانين بسعف النخيل وقراءة البشارات الأربع.",
    readings: "متى 21 — مرقس 11 — لوقا 19 — يوحنا 12.",
    image: feastPalmSunday,
    accent: "green",
  },
  {
    id: "thomas-sunday",
    title: "أحد توما",
    subtitle: "ذكرى ظهور السيد المسيح لتوما",
    category: "feast",
    copticDay: "24",
    copticYear: "1741 ش",
    gregorianDate: "برمهات",
    description: "ظهور الرب للقديس توما الرسول بعد القيامة بثمانية أيام.",
    about: "ظهر الرب لتلاميذه ومعهم توما، وأكد له قيامته فآمن وقال 'ربي وإلهي'.",
    rite: "قداس أحد توما بطقس الخمسين المقدسة.",
    readings: "يوحنا 20 — أعمال 5.",
    image: feastThomas,
    accent: "blue",
  },
  // ===== Fasting seasons =====
  {
    id: "great-fast",
    title: "الصوم الكبير",
    subtitle: "أربعون يوماً على مثال صوم الرب",
    category: "fast",
    copticDay: "—",
    copticYear: "1741 ش",
    gregorianDate: "أمشير",
    description: "أعظم أصوام الكنيسة، استعداداً لعيد القيامة.",
    about: "الصوم الكبير هو أربعون يوماً يصومها المؤمنون على مثال صوم السيد المسيح في البرية، يسبقه أسبوع الاستعداد ويتبعه أسبوع الآلام.",
    rite: "صلوات الصوم الكبير بطقس خاص حزايني وسجدات يومية.",
    readings: "قراءات سفر التكوين والأمثال يومياً + إنجيل القداس.",
    image: feastLastSupper,
    accent: "purple",
  },
  {
    id: "apostles-fast",
    title: "صوم الرسل",
    subtitle: "صوم الآباء الرسل قبل عيد استشهادهم",
    category: "fast",
    copticDay: "—",
    copticYear: "1741 ش",
    gregorianDate: "بؤونة",
    description: "يبدأ بعد عيد العنصرة وينتهي بعيد بطرس وبولس.",
    about: "صامه الآباء الرسل بعد حلول الروح القدس قبل الذهاب للكرازة.",
    rite: "طقس صيامي يومي حتى يوم العيد.",
    readings: "أعمال الرسل + رسائل بولس.",
    image: feastHolyLight,
    accent: "gold",
  },
  // ===== Saint commemorations =====
  {
    id: "st-mary-commem",
    title: "تذكار العذراء مريم",
    subtitle: "أم النور القديسة مريم العذراء",
    category: "saint",
    copticDay: "21",
    copticYear: "1741 ش",
    gregorianDate: "كل شهر",
    description: "تذكار شهري للسيدة العذراء.",
    about: "تكرم الكنيسة القديسة مريم العذراء في الحادي والعشرين من كل شهر قبطي.",
    rite: "قداس بطقس مريمي وذكصولوجية خاصة.",
    readings: "إشعياء 7 — لوقا 1.",
    image: feastEmptyTomb,
    accent: "blue",
  },
  {
    id: "st-mark-commem",
    title: "تذكار الشهيد مارمرقس",
    subtitle: "كاروز الديار المصرية",
    category: "saint",
    copticDay: "30",
    copticYear: "1741 ش",
    gregorianDate: "برمودة",
    description: "تذكار استشهاد القديس مارمرقس الرسول.",
    about: "بشّر مارمرقس بالمسيحية في مصر وأسس الكنيسة القبطية ثم استشهد في الإسكندرية.",
    rite: "قداس بطقس استشهاد وقراءة سيرته.",
    readings: "مرقس 16 — أعمال 12.",
    image: feastCrucifixion,
    accent: "gold",
  },
  // ===== Church occasions =====
  {
    id: "new-year-coptic",
    title: "رأس السنة القبطية",
    subtitle: "عيد النيروز — بداية السنة القبطية",
    category: "occasion",
    copticDay: "1",
    copticYear: "1741 ش",
    gregorianDate: "توت",
    description: "بداية السنة القبطية وذكرى الشهداء.",
    about: "تبدأ السنة القبطية بشهر توت، وتسمى أيضاً عيد النيروز تذكاراً لشهداء عصر الاستشهاد.",
    rite: "قداس عيد بطقس فرايحي وتوزيع البلح الأحمر والجوافة.",
    readings: "رؤيا 7 — متى 5.",
    image: feastPalmSunday,
    accent: "green",
  },
  {
    id: "consecration",
    title: "تكريس الميرون المقدس",
    subtitle: "مناسبة كنسية كبرى",
    category: "occasion",
    copticDay: "—",
    copticYear: "1741 ش",
    gregorianDate: "كل 7 سنوات",
    description: "تكريس الزيت المقدس بيد البابا.",
    about: "يُكرَّس الميرون المقدس كل سبع سنوات تقريباً، ويُستخدم في سر الميرون والتدشين.",
    rite: "طقس تكريس بحضور الآباء الأساقفة.",
    readings: "خروج 30 — لوقا 4.",
    image: feastThomas,
    accent: "purple",
  },
];

export const getFeast = (id: string) => FEASTS.find((f) => f.id === id) ?? FEASTS[0];
export const getTodayFeast = () => FEASTS[0];

export const CATEGORIES: { id: FeastCategory | "all"; label: string }[] = [
  { id: "all", label: "الكل" },
  { id: "feast", label: "الأعياد" },
  { id: "fast", label: "أصوام" },
  { id: "saint", label: "قديسين" },
  { id: "occasion", label: "مناسبات" },
];
