/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as BookRouteImport } from './routes/$book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/$book.index'
import { Route as BookChapterRouteImport } from './routes/$book.$chapter'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookChapterRoute = BookChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => BookRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$book': typeof BookRouteWithChildren
  '/bible': typeof BibleRoute
  '/books': typeof BooksRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/$book/$chapter': typeof BookChapterRoute
  '/$book/': typeof BookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/books': typeof BooksRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/$book/$chapter': typeof BookChapterRoute
  '/$book': typeof BookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$book': typeof BookRouteWithChildren
  '/bible': typeof BibleRoute
  '/books': typeof BooksRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/$book/$chapter': typeof BookChapterRoute
  '/$book/': typeof BookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$book'
    | '/bible'
    | '/books'
    | '/diagnostics'
    | '/home'
    | '/onboarding'
    | '/$book/$chapter'
    | '/$book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bible'
    | '/books'
    | '/diagnostics'
    | '/home'
    | '/onboarding'
    | '/$book/$chapter'
    | '/$book'
  id:
    | '__root__'
    | '/'
    | '/$book'
    | '/bible'
    | '/books'
    | '/diagnostics'
    | '/home'
    | '/onboarding'
    | '/$book/$chapter'
    | '/$book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  BibleRoute: typeof BibleRoute
  BooksRoute: typeof BooksRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book': {
      id: '/$book'
      path: '/$book'
      fullPath: '/$book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book/': {
      id: '/$book/'
      path: '/'
      fullPath: '/$book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/$book/$chapter': {
      id: '/$book/$chapter'
      path: '/$chapter'
      fullPath: '/$book/$chapter'
      preLoaderRoute: typeof BookChapterRouteImport
      parentRoute: typeof BookRoute
    }
  }
}

interface BookRouteChildren {
  BookChapterRoute: typeof BookChapterRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookChapterRoute: BookChapterRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  BibleRoute: BibleRoute,
  BooksRoute: BooksRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
