/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrayerRequestsRouteImport } from './routes/prayer-requests'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PersonalCallRouteImport } from './routes/personal-call'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MeditationsRouteImport } from './routes/meditations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as KatamerosTestRouteImport } from './routes/katameros-test'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ChurchesDirectoryRouteImport } from './routes/churches-directory'
import { Route as ChurchFeedLabRouteImport } from './routes/church-feed-lab'
import { Route as ChurchRouteImport } from './routes/church'
import { Route as CallRouteImport } from './routes/call'
import { Route as BooksV2RouteImport } from './routes/books-v2'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BibleLovableRouteImport } from './routes/bible-lovable'
import { Route as Bible2RouteImport } from './routes/bible-2'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AlphaConnectRouteImport } from './routes/alpha-connect'
import { Route as BookRouteImport } from './routes/$book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SynaxariumIndexRouteImport } from './routes/synaxarium.index'
import { Route as PublisherIndexRouteImport } from './routes/publisher.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as KholagyIndexRouteImport } from './routes/kholagy.index'
import { Route as KatamerosIndexRouteImport } from './routes/katameros.index'
import { Route as FeastsIndexRouteImport } from './routes/feasts.index'
import { Route as BibleIndexRouteImport } from './routes/bible.index'
import { Route as AgpeyaIndexRouteImport } from './routes/agpeya.index'
import { Route as BookIndexRouteImport } from './routes/$book.index'
import { Route as SynaxariumSaintIdRouteImport } from './routes/synaxarium.$saintId'
import { Route as SettingsTrustRouteImport } from './routes/settings.trust'
import { Route as PublisherApplyRouteImport } from './routes/publisher.apply'
import { Route as PublisherPublisherIdRouteImport } from './routes/publisher.$publisherId'
import { Route as ProfileServiceRouteImport } from './routes/profile.service'
import { Route as ProfileSecurityRouteImport } from './routes/profile.security'
import { Route as ProfilePersonalRouteImport } from './routes/profile.personal'
import { Route as ProfileMessagesRouteImport } from './routes/profile.messages'
import { Route as ProfileMembershipRouteImport } from './routes/profile.membership'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileContributionsRouteImport } from './routes/profile.contributions'
import { Route as ProfileChurchRouteImport } from './routes/profile.church'
import { Route as ProfileAppearanceRouteImport } from './routes/profile.appearance'
import { Route as PlatformSettingsRouteImport } from './routes/platform.settings'
import { Route as PlatformScanRouteImport } from './routes/platform.scan'
import { Route as PlatformReportsRouteImport } from './routes/platform.reports'
import { Route as PlatformPublisherCenterRouteImport } from './routes/platform.publisher-center'
import { Route as PlatformPrivacyRouteImport } from './routes/platform.privacy'
import { Route as PlatformOwnerSecurityRouteImport } from './routes/platform.owner-security'
import { Route as PlatformMonasteriesRouteImport } from './routes/platform.monasteries'
import { Route as PlatformModulesRouteImport } from './routes/platform.modules'
import { Route as PlatformLibraryRouteImport } from './routes/platform.library'
import { Route as PlatformEmergencyRouteImport } from './routes/platform.emergency'
import { Route as PlatformContentReviewRouteImport } from './routes/platform.content-review'
import { Route as PlatformChurchesRouteImport } from './routes/platform.churches'
import { Route as PlatformChurchLocationsRouteImport } from './routes/platform.church-locations'
import { Route as PlatformAuditRouteImport } from './routes/platform.audit'
import { Route as PlatformApprovalsRouteImport } from './routes/platform.approvals'
import { Route as PlatformAnalyticsRouteImport } from './routes/platform.analytics'
import { Route as PlatformAiRouteImport } from './routes/platform.ai'
import { Route as KholagyGroupIdRouteImport } from './routes/kholagy.$groupId'
import { Route as FeastsEventIdRouteImport } from './routes/feasts.$eventId'
import { Route as DevKatamerosCurvePreviewRouteImport } from './routes/dev.katameros-curve-preview'
import { Route as DevBackgroundPreviewRouteImport } from './routes/dev.background-preview'
import { Route as DevAuthRouteImport } from './routes/dev.auth'
import { Route as ChurchServiceRouteImport } from './routes/church.service'
import { Route as ChurchNotificationsRouteImport } from './routes/church.notifications'
import { Route as ChurchDirectoryRouteImport } from './routes/church.directory'
import { Route as ChurchArchiveRouteImport } from './routes/church.archive'
import { Route as BibleTodayRouteImport } from './routes/bible.today'
import { Route as BibleTimelineRouteImport } from './routes/bible.timeline'
import { Route as BibleSearchRouteImport } from './routes/bible.search'
import { Route as BibleSavedRouteImport } from './routes/bible.saved'
import { Route as BibleQuestionsRouteImport } from './routes/bible.questions'
import { Route as BiblePsalmsRouteImport } from './routes/bible.psalms'
import { Route as BiblePlacesRouteImport } from './routes/bible.places'
import { Route as BibleNotesRouteImport } from './routes/bible.notes'
import { Route as BibleJourneyRouteImport } from './routes/bible.journey'
import { Route as BibleCharactersRouteImport } from './routes/bible.characters'
import { Route as Audiov2PublisherIdRouteImport } from './routes/audiov2.$publisherId'
import { Route as AlphaConnectNearbyRouteImport } from './routes/alpha-connect.nearby'
import { Route as AgpeyaSavedRouteImport } from './routes/agpeya.saved'
import { Route as AgpeyaPrayerIdRouteImport } from './routes/agpeya.$prayerId'
import { Route as BookChapterRouteImport } from './routes/$book.$chapter'
import { Route as PublisherWorkspacePublisherIdRouteImport } from './routes/publisher.workspace.$publisherId'
import { Route as PublisherPreviewPublisherIdRouteImport } from './routes/publisher.preview.$publisherId'
import { Route as ProfileChurchSetupRouteImport } from './routes/profile.church.setup'
import { Route as PlatformApprovalsIdRouteImport } from './routes/platform.approvals.$id'
import { Route as MessagesChatContactIdRouteImport } from './routes/messages.chat.$contactId'
import { Route as KholagyLiturgyLiturgyKeyRouteImport } from './routes/kholagy.liturgy.$liturgyKey'
import { Route as KholagyCategoryCategoryRouteImport } from './routes/kholagy.category.$category'
import { Route as ChurchPostsTypeRouteImport } from './routes/church.posts.$type'
import { Route as ChurchPostIdRouteImport } from './routes/church.post.$id'
import { Route as ChurchDirectoryPlaceIdRouteImport } from './routes/church.directory.$placeId'
import { Route as ChurchChatContactIdRouteImport } from './routes/church.chat.$contactId'
import { Route as Audiov2PreviewPublisherIdRouteImport } from './routes/audiov2.preview.$publisherId'
import { Route as PublisherPublisherIdAlbumContentIdRouteImport } from './routes/publisher.$publisherId.album.$contentId'
import { Route as PlatformScanTrustTrustIdRouteImport } from './routes/platform.scan.trust.$trustId'
import { Route as KholagyLiturgyLiturgyKeySectionIdRouteImport } from './routes/kholagy.liturgy_.$liturgyKey.$sectionId'
import { Route as ChurchDirectoryPlaceIdPostsTypeRouteImport } from './routes/church.directory.$placeId.posts.$type'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRequestsRoute = PrayerRequestsRouteImport.update({
  id: '/prayer-requests',
  path: '/prayer-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalCallRoute = PersonalCallRouteImport.update({
  id: '/personal-call',
  path: '/personal-call',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationsRoute = MeditationsRouteImport.update({
  id: '/meditations',
  path: '/meditations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const KatamerosTestRoute = KatamerosTestRouteImport.update({
  id: '/katameros-test',
  path: '/katameros-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchesDirectoryRoute = ChurchesDirectoryRouteImport.update({
  id: '/churches-directory',
  path: '/churches-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchFeedLabRoute = ChurchFeedLabRouteImport.update({
  id: '/church-feed-lab',
  path: '/church-feed-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchRoute = ChurchRouteImport.update({
  id: '/church',
  path: '/church',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksV2Route = BooksV2RouteImport.update({
  id: '/books-v2',
  path: '/books-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleLovableRoute = BibleLovableRouteImport.update({
  id: '/bible-lovable',
  path: '/bible-lovable',
  getParentRoute: () => rootRouteImport,
} as any)
const Bible2Route = Bible2RouteImport.update({
  id: '/bible-2',
  path: '/bible-2',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaConnectRoute = AlphaConnectRouteImport.update({
  id: '/alpha-connect',
  path: '/alpha-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/$book',
  path: '/$book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SynaxariumIndexRoute = SynaxariumIndexRouteImport.update({
  id: '/synaxarium/',
  path: '/synaxarium/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherIndexRoute = PublisherIndexRouteImport.update({
  id: '/publisher/',
  path: '/publisher/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const KholagyIndexRoute = KholagyIndexRouteImport.update({
  id: '/kholagy/',
  path: '/kholagy/',
  getParentRoute: () => rootRouteImport,
} as any)
const KatamerosIndexRoute = KatamerosIndexRouteImport.update({
  id: '/katameros/',
  path: '/katameros/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeastsIndexRoute = FeastsIndexRouteImport.update({
  id: '/feasts/',
  path: '/feasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibleRoute,
} as any)
const AgpeyaIndexRoute = AgpeyaIndexRouteImport.update({
  id: '/agpeya/',
  path: '/agpeya/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const SynaxariumSaintIdRoute = SynaxariumSaintIdRouteImport.update({
  id: '/synaxarium/$saintId',
  path: '/synaxarium/$saintId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTrustRoute = SettingsTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => SettingsRoute,
} as any)
const PublisherApplyRoute = PublisherApplyRouteImport.update({
  id: '/publisher/apply',
  path: '/publisher/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherPublisherIdRoute = PublisherPublisherIdRouteImport.update({
  id: '/publisher/$publisherId',
  path: '/publisher/$publisherId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileServiceRoute = ProfileServiceRouteImport.update({
  id: '/profile/service',
  path: '/profile/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/profile/security',
  path: '/profile/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/profile/personal',
  path: '/profile/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMessagesRoute = ProfileMessagesRouteImport.update({
  id: '/profile/messages',
  path: '/profile/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileMembershipRoute = ProfileMembershipRouteImport.update({
  id: '/profile/membership',
  path: '/profile/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileContributionsRoute = ProfileContributionsRouteImport.update({
  id: '/profile/contributions',
  path: '/profile/contributions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileChurchRoute = ProfileChurchRouteImport.update({
  id: '/profile/church',
  path: '/profile/church',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAppearanceRoute = ProfileAppearanceRouteImport.update({
  id: '/profile/appearance',
  path: '/profile/appearance',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSettingsRoute = PlatformSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformScanRoute = PlatformScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformReportsRoute = PlatformReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPublisherCenterRoute = PlatformPublisherCenterRouteImport.update({
  id: '/publisher-center',
  path: '/publisher-center',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPrivacyRoute = PlatformPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOwnerSecurityRoute = PlatformOwnerSecurityRouteImport.update({
  id: '/owner-security',
  path: '/owner-security',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformMonasteriesRoute = PlatformMonasteriesRouteImport.update({
  id: '/monasteries',
  path: '/monasteries',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformModulesRoute = PlatformModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLibraryRoute = PlatformLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformEmergencyRoute = PlatformEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformContentReviewRoute = PlatformContentReviewRouteImport.update({
  id: '/content-review',
  path: '/content-review',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformChurchesRoute = PlatformChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformChurchLocationsRoute = PlatformChurchLocationsRouteImport.update({
  id: '/church-locations',
  path: '/church-locations',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAuditRoute = PlatformAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformApprovalsRoute = PlatformApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAnalyticsRoute = PlatformAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAiRoute = PlatformAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PlatformRoute,
} as any)
const KholagyGroupIdRoute = KholagyGroupIdRouteImport.update({
  id: '/kholagy/$groupId',
  path: '/kholagy/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const FeastsEventIdRoute = FeastsEventIdRouteImport.update({
  id: '/feasts/$eventId',
  path: '/feasts/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevKatamerosCurvePreviewRoute =
  DevKatamerosCurvePreviewRouteImport.update({
    id: '/dev/katameros-curve-preview',
    path: '/dev/katameros-curve-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevBackgroundPreviewRoute = DevBackgroundPreviewRouteImport.update({
  id: '/dev/background-preview',
  path: '/dev/background-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAuthRoute = DevAuthRouteImport.update({
  id: '/dev/auth',
  path: '/dev/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchServiceRoute = ChurchServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => ChurchRoute,
} as any)
const ChurchNotificationsRoute = ChurchNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ChurchRoute,
} as any)
const ChurchDirectoryRoute = ChurchDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => ChurchRoute,
} as any)
const ChurchArchiveRoute = ChurchArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ChurchRoute,
} as any)
const BibleTodayRoute = BibleTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => BibleRoute,
} as any)
const BibleTimelineRoute = BibleTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => BibleRoute,
} as any)
const BibleSearchRoute = BibleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BibleRoute,
} as any)
const BibleSavedRoute = BibleSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => BibleRoute,
} as any)
const BibleQuestionsRoute = BibleQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => BibleRoute,
} as any)
const BiblePsalmsRoute = BiblePsalmsRouteImport.update({
  id: '/psalms',
  path: '/psalms',
  getParentRoute: () => BibleRoute,
} as any)
const BiblePlacesRoute = BiblePlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => BibleRoute,
} as any)
const BibleNotesRoute = BibleNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => BibleRoute,
} as any)
const BibleJourneyRoute = BibleJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => BibleRoute,
} as any)
const BibleCharactersRoute = BibleCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => BibleRoute,
} as any)
const Audiov2PublisherIdRoute = Audiov2PublisherIdRouteImport.update({
  id: '/audiov2/$publisherId',
  path: '/audiov2/$publisherId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphaConnectNearbyRoute = AlphaConnectNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AlphaConnectRoute,
} as any)
const AgpeyaSavedRoute = AgpeyaSavedRouteImport.update({
  id: '/agpeya/saved',
  path: '/agpeya/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AgpeyaPrayerIdRoute = AgpeyaPrayerIdRouteImport.update({
  id: '/agpeya/$prayerId',
  path: '/agpeya/$prayerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterRoute = BookChapterRouteImport.update({
  id: '/$chapter',
  path: '/$chapter',
  getParentRoute: () => BookRoute,
} as any)
const PublisherWorkspacePublisherIdRoute =
  PublisherWorkspacePublisherIdRouteImport.update({
    id: '/publisher/workspace/$publisherId',
    path: '/publisher/workspace/$publisherId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherPreviewPublisherIdRoute =
  PublisherPreviewPublisherIdRouteImport.update({
    id: '/publisher/preview/$publisherId',
    path: '/publisher/preview/$publisherId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileChurchSetupRoute = ProfileChurchSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ProfileChurchRoute,
} as any)
const PlatformApprovalsIdRoute = PlatformApprovalsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlatformApprovalsRoute,
} as any)
const MessagesChatContactIdRoute = MessagesChatContactIdRouteImport.update({
  id: '/chat/$contactId',
  path: '/chat/$contactId',
  getParentRoute: () => MessagesRoute,
} as any)
const KholagyLiturgyLiturgyKeyRoute =
  KholagyLiturgyLiturgyKeyRouteImport.update({
    id: '/kholagy/liturgy/$liturgyKey',
    path: '/kholagy/liturgy/$liturgyKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const KholagyCategoryCategoryRoute = KholagyCategoryCategoryRouteImport.update({
  id: '/kholagy/category/$category',
  path: '/kholagy/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurchPostsTypeRoute = ChurchPostsTypeRouteImport.update({
  id: '/posts/$type',
  path: '/posts/$type',
  getParentRoute: () => ChurchRoute,
} as any)
const ChurchPostIdRoute = ChurchPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => ChurchRoute,
} as any)
const ChurchDirectoryPlaceIdRoute = ChurchDirectoryPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => ChurchDirectoryRoute,
} as any)
const ChurchChatContactIdRoute = ChurchChatContactIdRouteImport.update({
  id: '/chat/$contactId',
  path: '/chat/$contactId',
  getParentRoute: () => ChurchRoute,
} as any)
const Audiov2PreviewPublisherIdRoute =
  Audiov2PreviewPublisherIdRouteImport.update({
    id: '/audiov2/preview/$publisherId',
    path: '/audiov2/preview/$publisherId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublisherPublisherIdAlbumContentIdRoute =
  PublisherPublisherIdAlbumContentIdRouteImport.update({
    id: '/album/$contentId',
    path: '/album/$contentId',
    getParentRoute: () => PublisherPublisherIdRoute,
  } as any)
const PlatformScanTrustTrustIdRoute =
  PlatformScanTrustTrustIdRouteImport.update({
    id: '/trust/$trustId',
    path: '/trust/$trustId',
    getParentRoute: () => PlatformScanRoute,
  } as any)
const KholagyLiturgyLiturgyKeySectionIdRoute =
  KholagyLiturgyLiturgyKeySectionIdRouteImport.update({
    id: '/kholagy/liturgy_/$liturgyKey/$sectionId',
    path: '/kholagy/liturgy/$liturgyKey/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChurchDirectoryPlaceIdPostsTypeRoute =
  ChurchDirectoryPlaceIdPostsTypeRouteImport.update({
    id: '/posts/$type',
    path: '/posts/$type',
    getParentRoute: () => ChurchDirectoryPlaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$book': typeof BookRouteWithChildren
  '/alpha-connect': typeof AlphaConnectRouteWithChildren
  '/audio': typeof AudioRoute
  '/bible': typeof BibleRouteWithChildren
  '/bible-2': typeof Bible2Route
  '/bible-lovable': typeof BibleLovableRoute
  '/books': typeof BooksRoute
  '/books-v2': typeof BooksV2Route
  '/call': typeof CallRoute
  '/church': typeof ChurchRouteWithChildren
  '/church-feed-lab': typeof ChurchFeedLabRoute
  '/churches-directory': typeof ChurchesDirectoryRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/katameros-test': typeof KatamerosTestRoute
  '/kids': typeof KidsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/meditations': typeof MeditationsRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/personal-call': typeof PersonalCallRoute
  '/platform': typeof PlatformRouteWithChildren
  '/prayer-requests': typeof PrayerRequestsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$book/$chapter': typeof BookChapterRoute
  '/agpeya/$prayerId': typeof AgpeyaPrayerIdRoute
  '/agpeya/saved': typeof AgpeyaSavedRoute
  '/alpha-connect/nearby': typeof AlphaConnectNearbyRoute
  '/audiov2/$publisherId': typeof Audiov2PublisherIdRoute
  '/bible/characters': typeof BibleCharactersRoute
  '/bible/journey': typeof BibleJourneyRoute
  '/bible/notes': typeof BibleNotesRoute
  '/bible/places': typeof BiblePlacesRoute
  '/bible/psalms': typeof BiblePsalmsRoute
  '/bible/questions': typeof BibleQuestionsRoute
  '/bible/saved': typeof BibleSavedRoute
  '/bible/search': typeof BibleSearchRoute
  '/bible/timeline': typeof BibleTimelineRoute
  '/bible/today': typeof BibleTodayRoute
  '/church/archive': typeof ChurchArchiveRoute
  '/church/directory': typeof ChurchDirectoryRouteWithChildren
  '/church/notifications': typeof ChurchNotificationsRoute
  '/church/service': typeof ChurchServiceRoute
  '/dev/auth': typeof DevAuthRoute
  '/dev/background-preview': typeof DevBackgroundPreviewRoute
  '/dev/katameros-curve-preview': typeof DevKatamerosCurvePreviewRoute
  '/feasts/$eventId': typeof FeastsEventIdRoute
  '/kholagy/$groupId': typeof KholagyGroupIdRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/approvals': typeof PlatformApprovalsRouteWithChildren
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/church-locations': typeof PlatformChurchLocationsRoute
  '/platform/churches': typeof PlatformChurchesRoute
  '/platform/content-review': typeof PlatformContentReviewRoute
  '/platform/emergency': typeof PlatformEmergencyRoute
  '/platform/library': typeof PlatformLibraryRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/monasteries': typeof PlatformMonasteriesRoute
  '/platform/owner-security': typeof PlatformOwnerSecurityRoute
  '/platform/privacy': typeof PlatformPrivacyRoute
  '/platform/publisher-center': typeof PlatformPublisherCenterRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/scan': typeof PlatformScanRouteWithChildren
  '/platform/settings': typeof PlatformSettingsRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/profile/church': typeof ProfileChurchRouteWithChildren
  '/profile/contributions': typeof ProfileContributionsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/messages': typeof ProfileMessagesRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/service': typeof ProfileServiceRoute
  '/publisher/$publisherId': typeof PublisherPublisherIdRouteWithChildren
  '/publisher/apply': typeof PublisherApplyRoute
  '/settings/trust': typeof SettingsTrustRoute
  '/synaxarium/$saintId': typeof SynaxariumSaintIdRoute
  '/$book/': typeof BookIndexRoute
  '/agpeya/': typeof AgpeyaIndexRoute
  '/bible/': typeof BibleIndexRoute
  '/feasts/': typeof FeastsIndexRoute
  '/katameros/': typeof KatamerosIndexRoute
  '/kholagy/': typeof KholagyIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/synaxarium/': typeof SynaxariumIndexRoute
  '/audiov2/preview/$publisherId': typeof Audiov2PreviewPublisherIdRoute
  '/church/chat/$contactId': typeof ChurchChatContactIdRoute
  '/church/directory/$placeId': typeof ChurchDirectoryPlaceIdRouteWithChildren
  '/church/post/$id': typeof ChurchPostIdRoute
  '/church/posts/$type': typeof ChurchPostsTypeRoute
  '/kholagy/category/$category': typeof KholagyCategoryCategoryRoute
  '/kholagy/liturgy/$liturgyKey': typeof KholagyLiturgyLiturgyKeyRoute
  '/messages/chat/$contactId': typeof MessagesChatContactIdRoute
  '/platform/approvals/$id': typeof PlatformApprovalsIdRoute
  '/profile/church/setup': typeof ProfileChurchSetupRoute
  '/publisher/preview/$publisherId': typeof PublisherPreviewPublisherIdRoute
  '/publisher/workspace/$publisherId': typeof PublisherWorkspacePublisherIdRoute
  '/kholagy/liturgy/$liturgyKey/$sectionId': typeof KholagyLiturgyLiturgyKeySectionIdRoute
  '/platform/scan/trust/$trustId': typeof PlatformScanTrustTrustIdRoute
  '/publisher/$publisherId/album/$contentId': typeof PublisherPublisherIdAlbumContentIdRoute
  '/church/directory/$placeId/posts/$type': typeof ChurchDirectoryPlaceIdPostsTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alpha-connect': typeof AlphaConnectRouteWithChildren
  '/audio': typeof AudioRoute
  '/bible-2': typeof Bible2Route
  '/bible-lovable': typeof BibleLovableRoute
  '/books': typeof BooksRoute
  '/books-v2': typeof BooksV2Route
  '/call': typeof CallRoute
  '/church': typeof ChurchRouteWithChildren
  '/church-feed-lab': typeof ChurchFeedLabRoute
  '/churches-directory': typeof ChurchesDirectoryRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/katameros-test': typeof KatamerosTestRoute
  '/kids': typeof KidsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/meditations': typeof MeditationsRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/personal-call': typeof PersonalCallRoute
  '/prayer-requests': typeof PrayerRequestsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$book/$chapter': typeof BookChapterRoute
  '/agpeya/$prayerId': typeof AgpeyaPrayerIdRoute
  '/agpeya/saved': typeof AgpeyaSavedRoute
  '/alpha-connect/nearby': typeof AlphaConnectNearbyRoute
  '/audiov2/$publisherId': typeof Audiov2PublisherIdRoute
  '/bible/characters': typeof BibleCharactersRoute
  '/bible/journey': typeof BibleJourneyRoute
  '/bible/notes': typeof BibleNotesRoute
  '/bible/places': typeof BiblePlacesRoute
  '/bible/psalms': typeof BiblePsalmsRoute
  '/bible/questions': typeof BibleQuestionsRoute
  '/bible/saved': typeof BibleSavedRoute
  '/bible/search': typeof BibleSearchRoute
  '/bible/timeline': typeof BibleTimelineRoute
  '/bible/today': typeof BibleTodayRoute
  '/church/archive': typeof ChurchArchiveRoute
  '/church/directory': typeof ChurchDirectoryRouteWithChildren
  '/church/notifications': typeof ChurchNotificationsRoute
  '/church/service': typeof ChurchServiceRoute
  '/dev/auth': typeof DevAuthRoute
  '/dev/background-preview': typeof DevBackgroundPreviewRoute
  '/dev/katameros-curve-preview': typeof DevKatamerosCurvePreviewRoute
  '/feasts/$eventId': typeof FeastsEventIdRoute
  '/kholagy/$groupId': typeof KholagyGroupIdRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/approvals': typeof PlatformApprovalsRouteWithChildren
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/church-locations': typeof PlatformChurchLocationsRoute
  '/platform/churches': typeof PlatformChurchesRoute
  '/platform/content-review': typeof PlatformContentReviewRoute
  '/platform/emergency': typeof PlatformEmergencyRoute
  '/platform/library': typeof PlatformLibraryRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/monasteries': typeof PlatformMonasteriesRoute
  '/platform/owner-security': typeof PlatformOwnerSecurityRoute
  '/platform/privacy': typeof PlatformPrivacyRoute
  '/platform/publisher-center': typeof PlatformPublisherCenterRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/scan': typeof PlatformScanRouteWithChildren
  '/platform/settings': typeof PlatformSettingsRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/profile/church': typeof ProfileChurchRouteWithChildren
  '/profile/contributions': typeof ProfileContributionsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/messages': typeof ProfileMessagesRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/service': typeof ProfileServiceRoute
  '/publisher/$publisherId': typeof PublisherPublisherIdRouteWithChildren
  '/publisher/apply': typeof PublisherApplyRoute
  '/settings/trust': typeof SettingsTrustRoute
  '/synaxarium/$saintId': typeof SynaxariumSaintIdRoute
  '/$book': typeof BookIndexRoute
  '/agpeya': typeof AgpeyaIndexRoute
  '/bible': typeof BibleIndexRoute
  '/feasts': typeof FeastsIndexRoute
  '/katameros': typeof KatamerosIndexRoute
  '/kholagy': typeof KholagyIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/publisher': typeof PublisherIndexRoute
  '/synaxarium': typeof SynaxariumIndexRoute
  '/audiov2/preview/$publisherId': typeof Audiov2PreviewPublisherIdRoute
  '/church/chat/$contactId': typeof ChurchChatContactIdRoute
  '/church/directory/$placeId': typeof ChurchDirectoryPlaceIdRouteWithChildren
  '/church/post/$id': typeof ChurchPostIdRoute
  '/church/posts/$type': typeof ChurchPostsTypeRoute
  '/kholagy/category/$category': typeof KholagyCategoryCategoryRoute
  '/kholagy/liturgy/$liturgyKey': typeof KholagyLiturgyLiturgyKeyRoute
  '/messages/chat/$contactId': typeof MessagesChatContactIdRoute
  '/platform/approvals/$id': typeof PlatformApprovalsIdRoute
  '/profile/church/setup': typeof ProfileChurchSetupRoute
  '/publisher/preview/$publisherId': typeof PublisherPreviewPublisherIdRoute
  '/publisher/workspace/$publisherId': typeof PublisherWorkspacePublisherIdRoute
  '/kholagy/liturgy/$liturgyKey/$sectionId': typeof KholagyLiturgyLiturgyKeySectionIdRoute
  '/platform/scan/trust/$trustId': typeof PlatformScanTrustTrustIdRoute
  '/publisher/$publisherId/album/$contentId': typeof PublisherPublisherIdAlbumContentIdRoute
  '/church/directory/$placeId/posts/$type': typeof ChurchDirectoryPlaceIdPostsTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$book': typeof BookRouteWithChildren
  '/alpha-connect': typeof AlphaConnectRouteWithChildren
  '/audio': typeof AudioRoute
  '/bible': typeof BibleRouteWithChildren
  '/bible-2': typeof Bible2Route
  '/bible-lovable': typeof BibleLovableRoute
  '/books': typeof BooksRoute
  '/books-v2': typeof BooksV2Route
  '/call': typeof CallRoute
  '/church': typeof ChurchRouteWithChildren
  '/church-feed-lab': typeof ChurchFeedLabRoute
  '/churches-directory': typeof ChurchesDirectoryRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/katameros-test': typeof KatamerosTestRoute
  '/kids': typeof KidsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/meditations': typeof MeditationsRoute
  '/messages': typeof MessagesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/personal-call': typeof PersonalCallRoute
  '/platform': typeof PlatformRouteWithChildren
  '/prayer-requests': typeof PrayerRequestsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/$book/$chapter': typeof BookChapterRoute
  '/agpeya/$prayerId': typeof AgpeyaPrayerIdRoute
  '/agpeya/saved': typeof AgpeyaSavedRoute
  '/alpha-connect/nearby': typeof AlphaConnectNearbyRoute
  '/audiov2/$publisherId': typeof Audiov2PublisherIdRoute
  '/bible/characters': typeof BibleCharactersRoute
  '/bible/journey': typeof BibleJourneyRoute
  '/bible/notes': typeof BibleNotesRoute
  '/bible/places': typeof BiblePlacesRoute
  '/bible/psalms': typeof BiblePsalmsRoute
  '/bible/questions': typeof BibleQuestionsRoute
  '/bible/saved': typeof BibleSavedRoute
  '/bible/search': typeof BibleSearchRoute
  '/bible/timeline': typeof BibleTimelineRoute
  '/bible/today': typeof BibleTodayRoute
  '/church/archive': typeof ChurchArchiveRoute
  '/church/directory': typeof ChurchDirectoryRouteWithChildren
  '/church/notifications': typeof ChurchNotificationsRoute
  '/church/service': typeof ChurchServiceRoute
  '/dev/auth': typeof DevAuthRoute
  '/dev/background-preview': typeof DevBackgroundPreviewRoute
  '/dev/katameros-curve-preview': typeof DevKatamerosCurvePreviewRoute
  '/feasts/$eventId': typeof FeastsEventIdRoute
  '/kholagy/$groupId': typeof KholagyGroupIdRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/analytics': typeof PlatformAnalyticsRoute
  '/platform/approvals': typeof PlatformApprovalsRouteWithChildren
  '/platform/audit': typeof PlatformAuditRoute
  '/platform/church-locations': typeof PlatformChurchLocationsRoute
  '/platform/churches': typeof PlatformChurchesRoute
  '/platform/content-review': typeof PlatformContentReviewRoute
  '/platform/emergency': typeof PlatformEmergencyRoute
  '/platform/library': typeof PlatformLibraryRoute
  '/platform/modules': typeof PlatformModulesRoute
  '/platform/monasteries': typeof PlatformMonasteriesRoute
  '/platform/owner-security': typeof PlatformOwnerSecurityRoute
  '/platform/privacy': typeof PlatformPrivacyRoute
  '/platform/publisher-center': typeof PlatformPublisherCenterRoute
  '/platform/reports': typeof PlatformReportsRoute
  '/platform/scan': typeof PlatformScanRouteWithChildren
  '/platform/settings': typeof PlatformSettingsRoute
  '/profile/appearance': typeof ProfileAppearanceRoute
  '/profile/church': typeof ProfileChurchRouteWithChildren
  '/profile/contributions': typeof ProfileContributionsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/messages': typeof ProfileMessagesRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/service': typeof ProfileServiceRoute
  '/publisher/$publisherId': typeof PublisherPublisherIdRouteWithChildren
  '/publisher/apply': typeof PublisherApplyRoute
  '/settings/trust': typeof SettingsTrustRoute
  '/synaxarium/$saintId': typeof SynaxariumSaintIdRoute
  '/$book/': typeof BookIndexRoute
  '/agpeya/': typeof AgpeyaIndexRoute
  '/bible/': typeof BibleIndexRoute
  '/feasts/': typeof FeastsIndexRoute
  '/katameros/': typeof KatamerosIndexRoute
  '/kholagy/': typeof KholagyIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/publisher/': typeof PublisherIndexRoute
  '/synaxarium/': typeof SynaxariumIndexRoute
  '/audiov2/preview/$publisherId': typeof Audiov2PreviewPublisherIdRoute
  '/church/chat/$contactId': typeof ChurchChatContactIdRoute
  '/church/directory/$placeId': typeof ChurchDirectoryPlaceIdRouteWithChildren
  '/church/post/$id': typeof ChurchPostIdRoute
  '/church/posts/$type': typeof ChurchPostsTypeRoute
  '/kholagy/category/$category': typeof KholagyCategoryCategoryRoute
  '/kholagy/liturgy/$liturgyKey': typeof KholagyLiturgyLiturgyKeyRoute
  '/messages/chat/$contactId': typeof MessagesChatContactIdRoute
  '/platform/approvals/$id': typeof PlatformApprovalsIdRoute
  '/profile/church/setup': typeof ProfileChurchSetupRoute
  '/publisher/preview/$publisherId': typeof PublisherPreviewPublisherIdRoute
  '/publisher/workspace/$publisherId': typeof PublisherWorkspacePublisherIdRoute
  '/kholagy/liturgy_/$liturgyKey/$sectionId': typeof KholagyLiturgyLiturgyKeySectionIdRoute
  '/platform/scan/trust/$trustId': typeof PlatformScanTrustTrustIdRoute
  '/publisher/$publisherId/album/$contentId': typeof PublisherPublisherIdAlbumContentIdRoute
  '/church/directory/$placeId/posts/$type': typeof ChurchDirectoryPlaceIdPostsTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$book'
    | '/alpha-connect'
    | '/audio'
    | '/bible'
    | '/bible-2'
    | '/bible-lovable'
    | '/books'
    | '/books-v2'
    | '/call'
    | '/church'
    | '/church-feed-lab'
    | '/churches-directory'
    | '/diagnostics'
    | '/forgot-password'
    | '/home'
    | '/intro'
    | '/katameros-test'
    | '/kids'
    | '/library'
    | '/login'
    | '/meditations'
    | '/messages'
    | '/onboarding'
    | '/personal-call'
    | '/platform'
    | '/prayer-requests'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/$book/$chapter'
    | '/agpeya/$prayerId'
    | '/agpeya/saved'
    | '/alpha-connect/nearby'
    | '/audiov2/$publisherId'
    | '/bible/characters'
    | '/bible/journey'
    | '/bible/notes'
    | '/bible/places'
    | '/bible/psalms'
    | '/bible/questions'
    | '/bible/saved'
    | '/bible/search'
    | '/bible/timeline'
    | '/bible/today'
    | '/church/archive'
    | '/church/directory'
    | '/church/notifications'
    | '/church/service'
    | '/dev/auth'
    | '/dev/background-preview'
    | '/dev/katameros-curve-preview'
    | '/feasts/$eventId'
    | '/kholagy/$groupId'
    | '/platform/ai'
    | '/platform/analytics'
    | '/platform/approvals'
    | '/platform/audit'
    | '/platform/church-locations'
    | '/platform/churches'
    | '/platform/content-review'
    | '/platform/emergency'
    | '/platform/library'
    | '/platform/modules'
    | '/platform/monasteries'
    | '/platform/owner-security'
    | '/platform/privacy'
    | '/platform/publisher-center'
    | '/platform/reports'
    | '/platform/scan'
    | '/platform/settings'
    | '/profile/appearance'
    | '/profile/church'
    | '/profile/contributions'
    | '/profile/edit'
    | '/profile/membership'
    | '/profile/messages'
    | '/profile/personal'
    | '/profile/security'
    | '/profile/service'
    | '/publisher/$publisherId'
    | '/publisher/apply'
    | '/settings/trust'
    | '/synaxarium/$saintId'
    | '/$book/'
    | '/agpeya/'
    | '/bible/'
    | '/feasts/'
    | '/katameros/'
    | '/kholagy/'
    | '/platform/'
    | '/profile/'
    | '/publisher/'
    | '/synaxarium/'
    | '/audiov2/preview/$publisherId'
    | '/church/chat/$contactId'
    | '/church/directory/$placeId'
    | '/church/post/$id'
    | '/church/posts/$type'
    | '/kholagy/category/$category'
    | '/kholagy/liturgy/$liturgyKey'
    | '/messages/chat/$contactId'
    | '/platform/approvals/$id'
    | '/profile/church/setup'
    | '/publisher/preview/$publisherId'
    | '/publisher/workspace/$publisherId'
    | '/kholagy/liturgy/$liturgyKey/$sectionId'
    | '/platform/scan/trust/$trustId'
    | '/publisher/$publisherId/album/$contentId'
    | '/church/directory/$placeId/posts/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alpha-connect'
    | '/audio'
    | '/bible-2'
    | '/bible-lovable'
    | '/books'
    | '/books-v2'
    | '/call'
    | '/church'
    | '/church-feed-lab'
    | '/churches-directory'
    | '/diagnostics'
    | '/forgot-password'
    | '/home'
    | '/intro'
    | '/katameros-test'
    | '/kids'
    | '/library'
    | '/login'
    | '/meditations'
    | '/messages'
    | '/onboarding'
    | '/personal-call'
    | '/prayer-requests'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/$book/$chapter'
    | '/agpeya/$prayerId'
    | '/agpeya/saved'
    | '/alpha-connect/nearby'
    | '/audiov2/$publisherId'
    | '/bible/characters'
    | '/bible/journey'
    | '/bible/notes'
    | '/bible/places'
    | '/bible/psalms'
    | '/bible/questions'
    | '/bible/saved'
    | '/bible/search'
    | '/bible/timeline'
    | '/bible/today'
    | '/church/archive'
    | '/church/directory'
    | '/church/notifications'
    | '/church/service'
    | '/dev/auth'
    | '/dev/background-preview'
    | '/dev/katameros-curve-preview'
    | '/feasts/$eventId'
    | '/kholagy/$groupId'
    | '/platform/ai'
    | '/platform/analytics'
    | '/platform/approvals'
    | '/platform/audit'
    | '/platform/church-locations'
    | '/platform/churches'
    | '/platform/content-review'
    | '/platform/emergency'
    | '/platform/library'
    | '/platform/modules'
    | '/platform/monasteries'
    | '/platform/owner-security'
    | '/platform/privacy'
    | '/platform/publisher-center'
    | '/platform/reports'
    | '/platform/scan'
    | '/platform/settings'
    | '/profile/appearance'
    | '/profile/church'
    | '/profile/contributions'
    | '/profile/edit'
    | '/profile/membership'
    | '/profile/messages'
    | '/profile/personal'
    | '/profile/security'
    | '/profile/service'
    | '/publisher/$publisherId'
    | '/publisher/apply'
    | '/settings/trust'
    | '/synaxarium/$saintId'
    | '/$book'
    | '/agpeya'
    | '/bible'
    | '/feasts'
    | '/katameros'
    | '/kholagy'
    | '/platform'
    | '/profile'
    | '/publisher'
    | '/synaxarium'
    | '/audiov2/preview/$publisherId'
    | '/church/chat/$contactId'
    | '/church/directory/$placeId'
    | '/church/post/$id'
    | '/church/posts/$type'
    | '/kholagy/category/$category'
    | '/kholagy/liturgy/$liturgyKey'
    | '/messages/chat/$contactId'
    | '/platform/approvals/$id'
    | '/profile/church/setup'
    | '/publisher/preview/$publisherId'
    | '/publisher/workspace/$publisherId'
    | '/kholagy/liturgy/$liturgyKey/$sectionId'
    | '/platform/scan/trust/$trustId'
    | '/publisher/$publisherId/album/$contentId'
    | '/church/directory/$placeId/posts/$type'
  id:
    | '__root__'
    | '/'
    | '/$book'
    | '/alpha-connect'
    | '/audio'
    | '/bible'
    | '/bible-2'
    | '/bible-lovable'
    | '/books'
    | '/books-v2'
    | '/call'
    | '/church'
    | '/church-feed-lab'
    | '/churches-directory'
    | '/diagnostics'
    | '/forgot-password'
    | '/home'
    | '/intro'
    | '/katameros-test'
    | '/kids'
    | '/library'
    | '/login'
    | '/meditations'
    | '/messages'
    | '/onboarding'
    | '/personal-call'
    | '/platform'
    | '/prayer-requests'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/$book/$chapter'
    | '/agpeya/$prayerId'
    | '/agpeya/saved'
    | '/alpha-connect/nearby'
    | '/audiov2/$publisherId'
    | '/bible/characters'
    | '/bible/journey'
    | '/bible/notes'
    | '/bible/places'
    | '/bible/psalms'
    | '/bible/questions'
    | '/bible/saved'
    | '/bible/search'
    | '/bible/timeline'
    | '/bible/today'
    | '/church/archive'
    | '/church/directory'
    | '/church/notifications'
    | '/church/service'
    | '/dev/auth'
    | '/dev/background-preview'
    | '/dev/katameros-curve-preview'
    | '/feasts/$eventId'
    | '/kholagy/$groupId'
    | '/platform/ai'
    | '/platform/analytics'
    | '/platform/approvals'
    | '/platform/audit'
    | '/platform/church-locations'
    | '/platform/churches'
    | '/platform/content-review'
    | '/platform/emergency'
    | '/platform/library'
    | '/platform/modules'
    | '/platform/monasteries'
    | '/platform/owner-security'
    | '/platform/privacy'
    | '/platform/publisher-center'
    | '/platform/reports'
    | '/platform/scan'
    | '/platform/settings'
    | '/profile/appearance'
    | '/profile/church'
    | '/profile/contributions'
    | '/profile/edit'
    | '/profile/membership'
    | '/profile/messages'
    | '/profile/personal'
    | '/profile/security'
    | '/profile/service'
    | '/publisher/$publisherId'
    | '/publisher/apply'
    | '/settings/trust'
    | '/synaxarium/$saintId'
    | '/$book/'
    | '/agpeya/'
    | '/bible/'
    | '/feasts/'
    | '/katameros/'
    | '/kholagy/'
    | '/platform/'
    | '/profile/'
    | '/publisher/'
    | '/synaxarium/'
    | '/audiov2/preview/$publisherId'
    | '/church/chat/$contactId'
    | '/church/directory/$placeId'
    | '/church/post/$id'
    | '/church/posts/$type'
    | '/kholagy/category/$category'
    | '/kholagy/liturgy/$liturgyKey'
    | '/messages/chat/$contactId'
    | '/platform/approvals/$id'
    | '/profile/church/setup'
    | '/publisher/preview/$publisherId'
    | '/publisher/workspace/$publisherId'
    | '/kholagy/liturgy_/$liturgyKey/$sectionId'
    | '/platform/scan/trust/$trustId'
    | '/publisher/$publisherId/album/$contentId'
    | '/church/directory/$placeId/posts/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRouteWithChildren
  AlphaConnectRoute: typeof AlphaConnectRouteWithChildren
  AudioRoute: typeof AudioRoute
  BibleRoute: typeof BibleRouteWithChildren
  Bible2Route: typeof Bible2Route
  BibleLovableRoute: typeof BibleLovableRoute
  BooksRoute: typeof BooksRoute
  BooksV2Route: typeof BooksV2Route
  CallRoute: typeof CallRoute
  ChurchRoute: typeof ChurchRouteWithChildren
  ChurchFeedLabRoute: typeof ChurchFeedLabRoute
  ChurchesDirectoryRoute: typeof ChurchesDirectoryRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  KatamerosTestRoute: typeof KatamerosTestRoute
  KidsRoute: typeof KidsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MeditationsRoute: typeof MeditationsRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PersonalCallRoute: typeof PersonalCallRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  PrayerRequestsRoute: typeof PrayerRequestsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  AgpeyaPrayerIdRoute: typeof AgpeyaPrayerIdRoute
  AgpeyaSavedRoute: typeof AgpeyaSavedRoute
  Audiov2PublisherIdRoute: typeof Audiov2PublisherIdRoute
  DevAuthRoute: typeof DevAuthRoute
  DevBackgroundPreviewRoute: typeof DevBackgroundPreviewRoute
  DevKatamerosCurvePreviewRoute: typeof DevKatamerosCurvePreviewRoute
  FeastsEventIdRoute: typeof FeastsEventIdRoute
  KholagyGroupIdRoute: typeof KholagyGroupIdRoute
  ProfileAppearanceRoute: typeof ProfileAppearanceRoute
  ProfileChurchRoute: typeof ProfileChurchRouteWithChildren
  ProfileContributionsRoute: typeof ProfileContributionsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileMembershipRoute: typeof ProfileMembershipRoute
  ProfileMessagesRoute: typeof ProfileMessagesRoute
  ProfilePersonalRoute: typeof ProfilePersonalRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileServiceRoute: typeof ProfileServiceRoute
  PublisherPublisherIdRoute: typeof PublisherPublisherIdRouteWithChildren
  PublisherApplyRoute: typeof PublisherApplyRoute
  SynaxariumSaintIdRoute: typeof SynaxariumSaintIdRoute
  AgpeyaIndexRoute: typeof AgpeyaIndexRoute
  FeastsIndexRoute: typeof FeastsIndexRoute
  KatamerosIndexRoute: typeof KatamerosIndexRoute
  KholagyIndexRoute: typeof KholagyIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PublisherIndexRoute: typeof PublisherIndexRoute
  SynaxariumIndexRoute: typeof SynaxariumIndexRoute
  Audiov2PreviewPublisherIdRoute: typeof Audiov2PreviewPublisherIdRoute
  KholagyCategoryCategoryRoute: typeof KholagyCategoryCategoryRoute
  KholagyLiturgyLiturgyKeyRoute: typeof KholagyLiturgyLiturgyKeyRoute
  PublisherPreviewPublisherIdRoute: typeof PublisherPreviewPublisherIdRoute
  PublisherWorkspacePublisherIdRoute: typeof PublisherWorkspacePublisherIdRoute
  KholagyLiturgyLiturgyKeySectionIdRoute: typeof KholagyLiturgyLiturgyKeySectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-requests': {
      id: '/prayer-requests'
      path: '/prayer-requests'
      fullPath: '/prayer-requests'
      preLoaderRoute: typeof PrayerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-call': {
      id: '/personal-call'
      path: '/personal-call'
      fullPath: '/personal-call'
      preLoaderRoute: typeof PersonalCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditations': {
      id: '/meditations'
      path: '/meditations'
      fullPath: '/meditations'
      preLoaderRoute: typeof MeditationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katameros-test': {
      id: '/katameros-test'
      path: '/katameros-test'
      fullPath: '/katameros-test'
      preLoaderRoute: typeof KatamerosTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churches-directory': {
      id: '/churches-directory'
      path: '/churches-directory'
      fullPath: '/churches-directory'
      preLoaderRoute: typeof ChurchesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church-feed-lab': {
      id: '/church-feed-lab'
      path: '/church-feed-lab'
      fullPath: '/church-feed-lab'
      preLoaderRoute: typeof ChurchFeedLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church': {
      id: '/church'
      path: '/church'
      fullPath: '/church'
      preLoaderRoute: typeof ChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books-v2': {
      id: '/books-v2'
      path: '/books-v2'
      fullPath: '/books-v2'
      preLoaderRoute: typeof BooksV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-lovable': {
      id: '/bible-lovable'
      path: '/bible-lovable'
      fullPath: '/bible-lovable'
      preLoaderRoute: typeof BibleLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-2': {
      id: '/bible-2'
      path: '/bible-2'
      fullPath: '/bible-2'
      preLoaderRoute: typeof Bible2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha-connect': {
      id: '/alpha-connect'
      path: '/alpha-connect'
      fullPath: '/alpha-connect'
      preLoaderRoute: typeof AlphaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book': {
      id: '/$book'
      path: '/$book'
      fullPath: '/$book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synaxarium/': {
      id: '/synaxarium/'
      path: '/synaxarium'
      fullPath: '/synaxarium/'
      preLoaderRoute: typeof SynaxariumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/': {
      id: '/publisher/'
      path: '/publisher'
      fullPath: '/publisher/'
      preLoaderRoute: typeof PublisherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/kholagy/': {
      id: '/kholagy/'
      path: '/kholagy'
      fullPath: '/kholagy/'
      preLoaderRoute: typeof KholagyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katameros/': {
      id: '/katameros/'
      path: '/katameros'
      fullPath: '/katameros/'
      preLoaderRoute: typeof KatamerosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feasts/': {
      id: '/feasts/'
      path: '/feasts'
      fullPath: '/feasts/'
      preLoaderRoute: typeof FeastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/': {
      id: '/bible/'
      path: '/'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof BibleRoute
    }
    '/agpeya/': {
      id: '/agpeya/'
      path: '/agpeya'
      fullPath: '/agpeya/'
      preLoaderRoute: typeof AgpeyaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book/': {
      id: '/$book/'
      path: '/'
      fullPath: '/$book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/synaxarium/$saintId': {
      id: '/synaxarium/$saintId'
      path: '/synaxarium/$saintId'
      fullPath: '/synaxarium/$saintId'
      preLoaderRoute: typeof SynaxariumSaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/trust': {
      id: '/settings/trust'
      path: '/trust'
      fullPath: '/settings/trust'
      preLoaderRoute: typeof SettingsTrustRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/publisher/apply': {
      id: '/publisher/apply'
      path: '/publisher/apply'
      fullPath: '/publisher/apply'
      preLoaderRoute: typeof PublisherApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/$publisherId': {
      id: '/publisher/$publisherId'
      path: '/publisher/$publisherId'
      fullPath: '/publisher/$publisherId'
      preLoaderRoute: typeof PublisherPublisherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/service': {
      id: '/profile/service'
      path: '/profile/service'
      fullPath: '/profile/service'
      preLoaderRoute: typeof ProfileServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/personal': {
      id: '/profile/personal'
      path: '/profile/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof ProfilePersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/messages': {
      id: '/profile/messages'
      path: '/profile/messages'
      fullPath: '/profile/messages'
      preLoaderRoute: typeof ProfileMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/membership': {
      id: '/profile/membership'
      path: '/profile/membership'
      fullPath: '/profile/membership'
      preLoaderRoute: typeof ProfileMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/contributions': {
      id: '/profile/contributions'
      path: '/profile/contributions'
      fullPath: '/profile/contributions'
      preLoaderRoute: typeof ProfileContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/church': {
      id: '/profile/church'
      path: '/profile/church'
      fullPath: '/profile/church'
      preLoaderRoute: typeof ProfileChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/appearance': {
      id: '/profile/appearance'
      path: '/profile/appearance'
      fullPath: '/profile/appearance'
      preLoaderRoute: typeof ProfileAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/settings': {
      id: '/platform/settings'
      path: '/settings'
      fullPath: '/platform/settings'
      preLoaderRoute: typeof PlatformSettingsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/scan': {
      id: '/platform/scan'
      path: '/scan'
      fullPath: '/platform/scan'
      preLoaderRoute: typeof PlatformScanRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/reports': {
      id: '/platform/reports'
      path: '/reports'
      fullPath: '/platform/reports'
      preLoaderRoute: typeof PlatformReportsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/publisher-center': {
      id: '/platform/publisher-center'
      path: '/publisher-center'
      fullPath: '/platform/publisher-center'
      preLoaderRoute: typeof PlatformPublisherCenterRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/privacy': {
      id: '/platform/privacy'
      path: '/privacy'
      fullPath: '/platform/privacy'
      preLoaderRoute: typeof PlatformPrivacyRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/owner-security': {
      id: '/platform/owner-security'
      path: '/owner-security'
      fullPath: '/platform/owner-security'
      preLoaderRoute: typeof PlatformOwnerSecurityRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/monasteries': {
      id: '/platform/monasteries'
      path: '/monasteries'
      fullPath: '/platform/monasteries'
      preLoaderRoute: typeof PlatformMonasteriesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/modules': {
      id: '/platform/modules'
      path: '/modules'
      fullPath: '/platform/modules'
      preLoaderRoute: typeof PlatformModulesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/library': {
      id: '/platform/library'
      path: '/library'
      fullPath: '/platform/library'
      preLoaderRoute: typeof PlatformLibraryRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/emergency': {
      id: '/platform/emergency'
      path: '/emergency'
      fullPath: '/platform/emergency'
      preLoaderRoute: typeof PlatformEmergencyRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/content-review': {
      id: '/platform/content-review'
      path: '/content-review'
      fullPath: '/platform/content-review'
      preLoaderRoute: typeof PlatformContentReviewRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/churches': {
      id: '/platform/churches'
      path: '/churches'
      fullPath: '/platform/churches'
      preLoaderRoute: typeof PlatformChurchesRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/church-locations': {
      id: '/platform/church-locations'
      path: '/church-locations'
      fullPath: '/platform/church-locations'
      preLoaderRoute: typeof PlatformChurchLocationsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/audit': {
      id: '/platform/audit'
      path: '/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof PlatformAuditRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/approvals': {
      id: '/platform/approvals'
      path: '/approvals'
      fullPath: '/platform/approvals'
      preLoaderRoute: typeof PlatformApprovalsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/analytics': {
      id: '/platform/analytics'
      path: '/analytics'
      fullPath: '/platform/analytics'
      preLoaderRoute: typeof PlatformAnalyticsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/ai': {
      id: '/platform/ai'
      path: '/ai'
      fullPath: '/platform/ai'
      preLoaderRoute: typeof PlatformAiRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/kholagy/$groupId': {
      id: '/kholagy/$groupId'
      path: '/kholagy/$groupId'
      fullPath: '/kholagy/$groupId'
      preLoaderRoute: typeof KholagyGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feasts/$eventId': {
      id: '/feasts/$eventId'
      path: '/feasts/$eventId'
      fullPath: '/feasts/$eventId'
      preLoaderRoute: typeof FeastsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/katameros-curve-preview': {
      id: '/dev/katameros-curve-preview'
      path: '/dev/katameros-curve-preview'
      fullPath: '/dev/katameros-curve-preview'
      preLoaderRoute: typeof DevKatamerosCurvePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/background-preview': {
      id: '/dev/background-preview'
      path: '/dev/background-preview'
      fullPath: '/dev/background-preview'
      preLoaderRoute: typeof DevBackgroundPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/auth': {
      id: '/dev/auth'
      path: '/dev/auth'
      fullPath: '/dev/auth'
      preLoaderRoute: typeof DevAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church/service': {
      id: '/church/service'
      path: '/service'
      fullPath: '/church/service'
      preLoaderRoute: typeof ChurchServiceRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/church/notifications': {
      id: '/church/notifications'
      path: '/notifications'
      fullPath: '/church/notifications'
      preLoaderRoute: typeof ChurchNotificationsRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/church/directory': {
      id: '/church/directory'
      path: '/directory'
      fullPath: '/church/directory'
      preLoaderRoute: typeof ChurchDirectoryRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/church/archive': {
      id: '/church/archive'
      path: '/archive'
      fullPath: '/church/archive'
      preLoaderRoute: typeof ChurchArchiveRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/bible/today': {
      id: '/bible/today'
      path: '/today'
      fullPath: '/bible/today'
      preLoaderRoute: typeof BibleTodayRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/timeline': {
      id: '/bible/timeline'
      path: '/timeline'
      fullPath: '/bible/timeline'
      preLoaderRoute: typeof BibleTimelineRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/search': {
      id: '/bible/search'
      path: '/search'
      fullPath: '/bible/search'
      preLoaderRoute: typeof BibleSearchRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/saved': {
      id: '/bible/saved'
      path: '/saved'
      fullPath: '/bible/saved'
      preLoaderRoute: typeof BibleSavedRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/questions': {
      id: '/bible/questions'
      path: '/questions'
      fullPath: '/bible/questions'
      preLoaderRoute: typeof BibleQuestionsRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/psalms': {
      id: '/bible/psalms'
      path: '/psalms'
      fullPath: '/bible/psalms'
      preLoaderRoute: typeof BiblePsalmsRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/places': {
      id: '/bible/places'
      path: '/places'
      fullPath: '/bible/places'
      preLoaderRoute: typeof BiblePlacesRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/notes': {
      id: '/bible/notes'
      path: '/notes'
      fullPath: '/bible/notes'
      preLoaderRoute: typeof BibleNotesRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/journey': {
      id: '/bible/journey'
      path: '/journey'
      fullPath: '/bible/journey'
      preLoaderRoute: typeof BibleJourneyRouteImport
      parentRoute: typeof BibleRoute
    }
    '/bible/characters': {
      id: '/bible/characters'
      path: '/characters'
      fullPath: '/bible/characters'
      preLoaderRoute: typeof BibleCharactersRouteImport
      parentRoute: typeof BibleRoute
    }
    '/audiov2/$publisherId': {
      id: '/audiov2/$publisherId'
      path: '/audiov2/$publisherId'
      fullPath: '/audiov2/$publisherId'
      preLoaderRoute: typeof Audiov2PublisherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alpha-connect/nearby': {
      id: '/alpha-connect/nearby'
      path: '/nearby'
      fullPath: '/alpha-connect/nearby'
      preLoaderRoute: typeof AlphaConnectNearbyRouteImport
      parentRoute: typeof AlphaConnectRoute
    }
    '/agpeya/saved': {
      id: '/agpeya/saved'
      path: '/agpeya/saved'
      fullPath: '/agpeya/saved'
      preLoaderRoute: typeof AgpeyaSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agpeya/$prayerId': {
      id: '/agpeya/$prayerId'
      path: '/agpeya/$prayerId'
      fullPath: '/agpeya/$prayerId'
      preLoaderRoute: typeof AgpeyaPrayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$book/$chapter': {
      id: '/$book/$chapter'
      path: '/$chapter'
      fullPath: '/$book/$chapter'
      preLoaderRoute: typeof BookChapterRouteImport
      parentRoute: typeof BookRoute
    }
    '/publisher/workspace/$publisherId': {
      id: '/publisher/workspace/$publisherId'
      path: '/publisher/workspace/$publisherId'
      fullPath: '/publisher/workspace/$publisherId'
      preLoaderRoute: typeof PublisherWorkspacePublisherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/preview/$publisherId': {
      id: '/publisher/preview/$publisherId'
      path: '/publisher/preview/$publisherId'
      fullPath: '/publisher/preview/$publisherId'
      preLoaderRoute: typeof PublisherPreviewPublisherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/church/setup': {
      id: '/profile/church/setup'
      path: '/setup'
      fullPath: '/profile/church/setup'
      preLoaderRoute: typeof ProfileChurchSetupRouteImport
      parentRoute: typeof ProfileChurchRoute
    }
    '/platform/approvals/$id': {
      id: '/platform/approvals/$id'
      path: '/$id'
      fullPath: '/platform/approvals/$id'
      preLoaderRoute: typeof PlatformApprovalsIdRouteImport
      parentRoute: typeof PlatformApprovalsRoute
    }
    '/messages/chat/$contactId': {
      id: '/messages/chat/$contactId'
      path: '/chat/$contactId'
      fullPath: '/messages/chat/$contactId'
      preLoaderRoute: typeof MessagesChatContactIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/kholagy/liturgy/$liturgyKey': {
      id: '/kholagy/liturgy/$liturgyKey'
      path: '/kholagy/liturgy/$liturgyKey'
      fullPath: '/kholagy/liturgy/$liturgyKey'
      preLoaderRoute: typeof KholagyLiturgyLiturgyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kholagy/category/$category': {
      id: '/kholagy/category/$category'
      path: '/kholagy/category/$category'
      fullPath: '/kholagy/category/$category'
      preLoaderRoute: typeof KholagyCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church/posts/$type': {
      id: '/church/posts/$type'
      path: '/posts/$type'
      fullPath: '/church/posts/$type'
      preLoaderRoute: typeof ChurchPostsTypeRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/church/post/$id': {
      id: '/church/post/$id'
      path: '/post/$id'
      fullPath: '/church/post/$id'
      preLoaderRoute: typeof ChurchPostIdRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/church/directory/$placeId': {
      id: '/church/directory/$placeId'
      path: '/$placeId'
      fullPath: '/church/directory/$placeId'
      preLoaderRoute: typeof ChurchDirectoryPlaceIdRouteImport
      parentRoute: typeof ChurchDirectoryRoute
    }
    '/church/chat/$contactId': {
      id: '/church/chat/$contactId'
      path: '/chat/$contactId'
      fullPath: '/church/chat/$contactId'
      preLoaderRoute: typeof ChurchChatContactIdRouteImport
      parentRoute: typeof ChurchRoute
    }
    '/audiov2/preview/$publisherId': {
      id: '/audiov2/preview/$publisherId'
      path: '/audiov2/preview/$publisherId'
      fullPath: '/audiov2/preview/$publisherId'
      preLoaderRoute: typeof Audiov2PreviewPublisherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher/$publisherId/album/$contentId': {
      id: '/publisher/$publisherId/album/$contentId'
      path: '/album/$contentId'
      fullPath: '/publisher/$publisherId/album/$contentId'
      preLoaderRoute: typeof PublisherPublisherIdAlbumContentIdRouteImport
      parentRoute: typeof PublisherPublisherIdRoute
    }
    '/platform/scan/trust/$trustId': {
      id: '/platform/scan/trust/$trustId'
      path: '/trust/$trustId'
      fullPath: '/platform/scan/trust/$trustId'
      preLoaderRoute: typeof PlatformScanTrustTrustIdRouteImport
      parentRoute: typeof PlatformScanRoute
    }
    '/kholagy/liturgy_/$liturgyKey/$sectionId': {
      id: '/kholagy/liturgy_/$liturgyKey/$sectionId'
      path: '/kholagy/liturgy/$liturgyKey/$sectionId'
      fullPath: '/kholagy/liturgy/$liturgyKey/$sectionId'
      preLoaderRoute: typeof KholagyLiturgyLiturgyKeySectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/church/directory/$placeId/posts/$type': {
      id: '/church/directory/$placeId/posts/$type'
      path: '/posts/$type'
      fullPath: '/church/directory/$placeId/posts/$type'
      preLoaderRoute: typeof ChurchDirectoryPlaceIdPostsTypeRouteImport
      parentRoute: typeof ChurchDirectoryPlaceIdRoute
    }
  }
}

interface BookRouteChildren {
  BookChapterRoute: typeof BookChapterRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookChapterRoute: BookChapterRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface AlphaConnectRouteChildren {
  AlphaConnectNearbyRoute: typeof AlphaConnectNearbyRoute
}

const AlphaConnectRouteChildren: AlphaConnectRouteChildren = {
  AlphaConnectNearbyRoute: AlphaConnectNearbyRoute,
}

const AlphaConnectRouteWithChildren = AlphaConnectRoute._addFileChildren(
  AlphaConnectRouteChildren,
)

interface BibleRouteChildren {
  BibleCharactersRoute: typeof BibleCharactersRoute
  BibleJourneyRoute: typeof BibleJourneyRoute
  BibleNotesRoute: typeof BibleNotesRoute
  BiblePlacesRoute: typeof BiblePlacesRoute
  BiblePsalmsRoute: typeof BiblePsalmsRoute
  BibleQuestionsRoute: typeof BibleQuestionsRoute
  BibleSavedRoute: typeof BibleSavedRoute
  BibleSearchRoute: typeof BibleSearchRoute
  BibleTimelineRoute: typeof BibleTimelineRoute
  BibleTodayRoute: typeof BibleTodayRoute
  BibleIndexRoute: typeof BibleIndexRoute
}

const BibleRouteChildren: BibleRouteChildren = {
  BibleCharactersRoute: BibleCharactersRoute,
  BibleJourneyRoute: BibleJourneyRoute,
  BibleNotesRoute: BibleNotesRoute,
  BiblePlacesRoute: BiblePlacesRoute,
  BiblePsalmsRoute: BiblePsalmsRoute,
  BibleQuestionsRoute: BibleQuestionsRoute,
  BibleSavedRoute: BibleSavedRoute,
  BibleSearchRoute: BibleSearchRoute,
  BibleTimelineRoute: BibleTimelineRoute,
  BibleTodayRoute: BibleTodayRoute,
  BibleIndexRoute: BibleIndexRoute,
}

const BibleRouteWithChildren = BibleRoute._addFileChildren(BibleRouteChildren)

interface ChurchDirectoryPlaceIdRouteChildren {
  ChurchDirectoryPlaceIdPostsTypeRoute: typeof ChurchDirectoryPlaceIdPostsTypeRoute
}

const ChurchDirectoryPlaceIdRouteChildren: ChurchDirectoryPlaceIdRouteChildren =
  {
    ChurchDirectoryPlaceIdPostsTypeRoute: ChurchDirectoryPlaceIdPostsTypeRoute,
  }

const ChurchDirectoryPlaceIdRouteWithChildren =
  ChurchDirectoryPlaceIdRoute._addFileChildren(
    ChurchDirectoryPlaceIdRouteChildren,
  )

interface ChurchDirectoryRouteChildren {
  ChurchDirectoryPlaceIdRoute: typeof ChurchDirectoryPlaceIdRouteWithChildren
}

const ChurchDirectoryRouteChildren: ChurchDirectoryRouteChildren = {
  ChurchDirectoryPlaceIdRoute: ChurchDirectoryPlaceIdRouteWithChildren,
}

const ChurchDirectoryRouteWithChildren = ChurchDirectoryRoute._addFileChildren(
  ChurchDirectoryRouteChildren,
)

interface ChurchRouteChildren {
  ChurchArchiveRoute: typeof ChurchArchiveRoute
  ChurchDirectoryRoute: typeof ChurchDirectoryRouteWithChildren
  ChurchNotificationsRoute: typeof ChurchNotificationsRoute
  ChurchServiceRoute: typeof ChurchServiceRoute
  ChurchChatContactIdRoute: typeof ChurchChatContactIdRoute
  ChurchPostIdRoute: typeof ChurchPostIdRoute
  ChurchPostsTypeRoute: typeof ChurchPostsTypeRoute
}

const ChurchRouteChildren: ChurchRouteChildren = {
  ChurchArchiveRoute: ChurchArchiveRoute,
  ChurchDirectoryRoute: ChurchDirectoryRouteWithChildren,
  ChurchNotificationsRoute: ChurchNotificationsRoute,
  ChurchServiceRoute: ChurchServiceRoute,
  ChurchChatContactIdRoute: ChurchChatContactIdRoute,
  ChurchPostIdRoute: ChurchPostIdRoute,
  ChurchPostsTypeRoute: ChurchPostsTypeRoute,
}

const ChurchRouteWithChildren =
  ChurchRoute._addFileChildren(ChurchRouteChildren)

interface MessagesRouteChildren {
  MessagesChatContactIdRoute: typeof MessagesChatContactIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesChatContactIdRoute: MessagesChatContactIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface PlatformApprovalsRouteChildren {
  PlatformApprovalsIdRoute: typeof PlatformApprovalsIdRoute
}

const PlatformApprovalsRouteChildren: PlatformApprovalsRouteChildren = {
  PlatformApprovalsIdRoute: PlatformApprovalsIdRoute,
}

const PlatformApprovalsRouteWithChildren =
  PlatformApprovalsRoute._addFileChildren(PlatformApprovalsRouteChildren)

interface PlatformScanRouteChildren {
  PlatformScanTrustTrustIdRoute: typeof PlatformScanTrustTrustIdRoute
}

const PlatformScanRouteChildren: PlatformScanRouteChildren = {
  PlatformScanTrustTrustIdRoute: PlatformScanTrustTrustIdRoute,
}

const PlatformScanRouteWithChildren = PlatformScanRoute._addFileChildren(
  PlatformScanRouteChildren,
)

interface PlatformRouteChildren {
  PlatformAiRoute: typeof PlatformAiRoute
  PlatformAnalyticsRoute: typeof PlatformAnalyticsRoute
  PlatformApprovalsRoute: typeof PlatformApprovalsRouteWithChildren
  PlatformAuditRoute: typeof PlatformAuditRoute
  PlatformChurchLocationsRoute: typeof PlatformChurchLocationsRoute
  PlatformChurchesRoute: typeof PlatformChurchesRoute
  PlatformContentReviewRoute: typeof PlatformContentReviewRoute
  PlatformEmergencyRoute: typeof PlatformEmergencyRoute
  PlatformLibraryRoute: typeof PlatformLibraryRoute
  PlatformModulesRoute: typeof PlatformModulesRoute
  PlatformMonasteriesRoute: typeof PlatformMonasteriesRoute
  PlatformOwnerSecurityRoute: typeof PlatformOwnerSecurityRoute
  PlatformPrivacyRoute: typeof PlatformPrivacyRoute
  PlatformPublisherCenterRoute: typeof PlatformPublisherCenterRoute
  PlatformReportsRoute: typeof PlatformReportsRoute
  PlatformScanRoute: typeof PlatformScanRouteWithChildren
  PlatformSettingsRoute: typeof PlatformSettingsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAiRoute: PlatformAiRoute,
  PlatformAnalyticsRoute: PlatformAnalyticsRoute,
  PlatformApprovalsRoute: PlatformApprovalsRouteWithChildren,
  PlatformAuditRoute: PlatformAuditRoute,
  PlatformChurchLocationsRoute: PlatformChurchLocationsRoute,
  PlatformChurchesRoute: PlatformChurchesRoute,
  PlatformContentReviewRoute: PlatformContentReviewRoute,
  PlatformEmergencyRoute: PlatformEmergencyRoute,
  PlatformLibraryRoute: PlatformLibraryRoute,
  PlatformModulesRoute: PlatformModulesRoute,
  PlatformMonasteriesRoute: PlatformMonasteriesRoute,
  PlatformOwnerSecurityRoute: PlatformOwnerSecurityRoute,
  PlatformPrivacyRoute: PlatformPrivacyRoute,
  PlatformPublisherCenterRoute: PlatformPublisherCenterRoute,
  PlatformReportsRoute: PlatformReportsRoute,
  PlatformScanRoute: PlatformScanRouteWithChildren,
  PlatformSettingsRoute: PlatformSettingsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface SettingsRouteChildren {
  SettingsTrustRoute: typeof SettingsTrustRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsTrustRoute: SettingsTrustRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ProfileChurchRouteChildren {
  ProfileChurchSetupRoute: typeof ProfileChurchSetupRoute
}

const ProfileChurchRouteChildren: ProfileChurchRouteChildren = {
  ProfileChurchSetupRoute: ProfileChurchSetupRoute,
}

const ProfileChurchRouteWithChildren = ProfileChurchRoute._addFileChildren(
  ProfileChurchRouteChildren,
)

interface PublisherPublisherIdRouteChildren {
  PublisherPublisherIdAlbumContentIdRoute: typeof PublisherPublisherIdAlbumContentIdRoute
}

const PublisherPublisherIdRouteChildren: PublisherPublisherIdRouteChildren = {
  PublisherPublisherIdAlbumContentIdRoute:
    PublisherPublisherIdAlbumContentIdRoute,
}

const PublisherPublisherIdRouteWithChildren =
  PublisherPublisherIdRoute._addFileChildren(PublisherPublisherIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRouteWithChildren,
  AlphaConnectRoute: AlphaConnectRouteWithChildren,
  AudioRoute: AudioRoute,
  BibleRoute: BibleRouteWithChildren,
  Bible2Route: Bible2Route,
  BibleLovableRoute: BibleLovableRoute,
  BooksRoute: BooksRoute,
  BooksV2Route: BooksV2Route,
  CallRoute: CallRoute,
  ChurchRoute: ChurchRouteWithChildren,
  ChurchFeedLabRoute: ChurchFeedLabRoute,
  ChurchesDirectoryRoute: ChurchesDirectoryRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  KatamerosTestRoute: KatamerosTestRoute,
  KidsRoute: KidsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MeditationsRoute: MeditationsRoute,
  MessagesRoute: MessagesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PersonalCallRoute: PersonalCallRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PrayerRequestsRoute: PrayerRequestsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  AgpeyaPrayerIdRoute: AgpeyaPrayerIdRoute,
  AgpeyaSavedRoute: AgpeyaSavedRoute,
  Audiov2PublisherIdRoute: Audiov2PublisherIdRoute,
  DevAuthRoute: DevAuthRoute,
  DevBackgroundPreviewRoute: DevBackgroundPreviewRoute,
  DevKatamerosCurvePreviewRoute: DevKatamerosCurvePreviewRoute,
  FeastsEventIdRoute: FeastsEventIdRoute,
  KholagyGroupIdRoute: KholagyGroupIdRoute,
  ProfileAppearanceRoute: ProfileAppearanceRoute,
  ProfileChurchRoute: ProfileChurchRouteWithChildren,
  ProfileContributionsRoute: ProfileContributionsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileMembershipRoute: ProfileMembershipRoute,
  ProfileMessagesRoute: ProfileMessagesRoute,
  ProfilePersonalRoute: ProfilePersonalRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileServiceRoute: ProfileServiceRoute,
  PublisherPublisherIdRoute: PublisherPublisherIdRouteWithChildren,
  PublisherApplyRoute: PublisherApplyRoute,
  SynaxariumSaintIdRoute: SynaxariumSaintIdRoute,
  AgpeyaIndexRoute: AgpeyaIndexRoute,
  FeastsIndexRoute: FeastsIndexRoute,
  KatamerosIndexRoute: KatamerosIndexRoute,
  KholagyIndexRoute: KholagyIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PublisherIndexRoute: PublisherIndexRoute,
  SynaxariumIndexRoute: SynaxariumIndexRoute,
  Audiov2PreviewPublisherIdRoute: Audiov2PreviewPublisherIdRoute,
  KholagyCategoryCategoryRoute: KholagyCategoryCategoryRoute,
  KholagyLiturgyLiturgyKeyRoute: KholagyLiturgyLiturgyKeyRoute,
  PublisherPreviewPublisherIdRoute: PublisherPreviewPublisherIdRoute,
  PublisherWorkspacePublisherIdRoute: PublisherWorkspacePublisherIdRoute,
  KholagyLiturgyLiturgyKeySectionIdRoute:
    KholagyLiturgyLiturgyKeySectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
