-- ALPHA-107 Phase 0: unified page lifecycle (churches + monasteries + claims)

do $$
begin
  if not exists (select 1 from pg_type where typname = 'place_page_status') then
    create type public.place_page_status as enum (
      'inactive',
      'pending_claim',
      'verified',
      'suspended'
    );
  end if;
end $$;

-- Legacy monasteries seed table (pre-107) — add page lifecycle column
alter table public.monasteries
  add column if not exists page_status public.place_page_status not null default 'inactive';

alter table public.churches
  add column if not exists page_status public.place_page_status;

update public.churches
set page_status = case
  when coalesce(is_active, true) = false then 'suspended'::public.place_page_status
  when coalesce(is_verified, false) or coalesce(location_verified, false) then 'verified'::public.place_page_status
  else 'inactive'::public.place_page_status
end
where page_status is null;

alter table public.churches
  alter column page_status set default 'inactive'::public.place_page_status;

create index if not exists churches_page_status_idx on public.churches (page_status);

-- ---------------------------------------------------------------------------
-- Church claim requests
-- ---------------------------------------------------------------------------
create table if not exists public.church_claim_requests (
  id uuid primary key default gen_random_uuid(),
  church_id bigint not null references public.churches (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  note text,
  approval_id uuid references public.platform_approvals (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists church_claim_requests_church_idx on public.church_claim_requests (church_id);
create index if not exists church_claim_requests_user_idx on public.church_claim_requests (user_id);
create unique index if not exists church_claim_requests_one_pending_per_church
  on public.church_claim_requests (church_id)
  where status = 'pending';

-- ---------------------------------------------------------------------------
-- Monasteries (directory + page foundation)
-- ---------------------------------------------------------------------------
create table if not exists public.monasteries (
  id bigint generated by default as identity primary key,
  monastery_name text not null,
  english_name text,
  city text,
  governorate text,
  country text default 'Egypt',
  formatted_address text,
  description text,
  cover_image_url text,
  hero_image text,
  latitude numeric,
  longitude numeric,
  phone text,
  email text,
  website_url text,
  is_active boolean not null default true,
  page_status public.place_page_status not null default 'inactive',
  members_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists monasteries_page_status_idx on public.monasteries (page_status);
create index if not exists monasteries_active_idx on public.monasteries (is_active) where is_active = true;

create table if not exists public.monastery_claim_requests (
  id uuid primary key default gen_random_uuid(),
  monastery_id bigint not null references public.monasteries (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  note text,
  approval_id uuid references public.platform_approvals (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists monastery_claim_requests_one_pending_per_monastery
  on public.monastery_claim_requests (monastery_id)
  where status = 'pending';

-- ---------------------------------------------------------------------------
-- Directory view — expose page_status (keep is_active filter for list)
-- ---------------------------------------------------------------------------
drop view if exists public.church_directory;

create view public.church_directory
with (security_invoker = true) as
select
  c.id,
  c.church_name,
  c.patron_saint,
  c.city,
  c.governorate,
  c.country,
  c.church_logo,
  c.is_verified,
  c.page_status,
  c.latitude,
  c.longitude
from public.churches c
where c.is_active = true;

grant select on public.monasteries to anon, authenticated;
grant select on public.church_claim_requests to authenticated;
grant select on public.monastery_claim_requests to authenticated;

alter table public.church_claim_requests enable row level security;
alter table public.monastery_claim_requests enable row level security;

drop policy if exists church_claim_requests_select_own on public.church_claim_requests;
create policy church_claim_requests_select_own on public.church_claim_requests
  for select to authenticated using (auth.uid() = user_id);

drop policy if exists monastery_claim_requests_select_own on public.monastery_claim_requests;
create policy monastery_claim_requests_select_own on public.monastery_claim_requests
  for select to authenticated using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Submit church claim → pending_claim + platform approval queue
-- ---------------------------------------------------------------------------
create or replace function public.submit_church_claim(
  p_church_id bigint,
  p_note text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_church record;
  v_claim_id uuid;
  v_approval_id uuid;
  v_request_no text;
begin
  if v_user is null then
    raise exception 'not_authenticated';
  end if;

  select id, church_name, page_status, is_active
  into v_church
  from public.churches
  where id = p_church_id and is_active = true;

  if not found then
    raise exception 'church_not_found';
  end if;

  if v_church.page_status = 'verified' then
    raise exception 'already_verified';
  end if;

  if v_church.page_status = 'pending_claim' then
    raise exception 'claim_pending';
  end if;

  if exists (
    select 1 from public.church_claim_requests
    where church_id = p_church_id and status = 'pending'
  ) then
    raise exception 'claim_pending';
  end if;

  insert into public.church_claim_requests (church_id, user_id, note)
  values (p_church_id, v_user, nullif(btrim(p_note), ''))
  returning id into v_claim_id;

  v_request_no := 'CC-' || to_char(now(), 'YYYY') || '-' || lpad(floor(random() * 10000)::text, 4, '0');

  insert into public.platform_approvals (
    request_no, kind, title, kind_label, status, priority, payload
  )
  values (
    v_request_no,
    'church_claim',
    'طلب استلام — ' || v_church.church_name,
    'استلام كنيسة',
    'pending',
    'normal',
    jsonb_build_object(
      'churchId', p_church_id,
      'claimId', v_claim_id,
      'submittedBy', v_user::text,
      'note', coalesce(p_note, '')
    )
  )
  returning id into v_approval_id;

  update public.church_claim_requests
  set approval_id = v_approval_id, updated_at = now()
  where id = v_claim_id;

  update public.churches
  set page_status = 'pending_claim', updated_at = now()
  where id = p_church_id;

  return json_build_object(
    'ok', true,
    'claimId', v_claim_id,
    'approvalId', v_approval_id,
    'pageStatus', 'pending_claim'
  );
end;
$$;

grant execute on function public.submit_church_claim(bigint, text) to authenticated;

create or replace function public.get_church_claim_status(p_church_id bigint)
returns json
language sql
stable
security definer
set search_path = public
as $$
  select json_build_object(
    'pageStatus', c.page_status,
    'hasPendingClaim', exists (
      select 1 from public.church_claim_requests r
      where r.church_id = p_church_id and r.status = 'pending'
    ),
    'userHasPendingClaim', exists (
      select 1 from public.church_claim_requests r
      where r.church_id = p_church_id
        and r.status = 'pending'
        and r.user_id = auth.uid()
    )
  )
  from public.churches c
  where c.id = p_church_id;
$$;

grant execute on function public.get_church_claim_status(bigint) to anon, authenticated;
